<span metal:use-macro="header.phtml/header" />

<div class="span-14">
<!-- 	<tal:block content="structure helper:flashMessenger()" /> -->

	blabla
</div>

<div class="span-10 last">

	<div class="bigbox">
		<div class="title" i18n:translate="">Camps / Courses</div>
		<div class="content">blablabla</div>
	</div>

	<div class="bigbox">
		<div class="title" i18n:translate="">Open Requests</div>
		<div class="content">
			<tal:block repeat="user friendshipRequests">
		
				 <a tal:attributes="href helper:url(array('user' => user.getId()), 'user')" class="span-2">
					<img width="46" height="46" tal:attributes="src helper:url(array('controller' => 'avatar', 'action' => 'user', 'id' => user.getId(), 'size' =>32), 'general')" /><br />
				 </a>
				 
				 <div class="span-7 last">
					 <a tal:attributes="href helper:url(array('user' => user.getId()), 'user')" tal:content="user/getUsername" /> <span i18n:translate="">wants to be your friend</span>!<br/>
					 
					 <a class="button positive" tal:attributes="href helper:url(array('action' => 'accept', 'user' => user.getId()), 'user')">+<span i18n:translate="">accept</span></a>
					 <a class="button negative" tal:attributes="href helper:url(array('action' => 'ignore', 'user' => user.getId()), 'user')">-<span i18n:translate="">ignore</span></a>
				</div>
						
				<hr tal:condition="not: repeat/user/end" />
			</tal:block>
			
			<hr tal:condition="php: !friendshipRequests.isEmpty() && !membershipRequests.isEmpty()" />
			
			<tal:block repeat="usergroup membershipRequests">
				<span metal:use-macro="global/singleusergroup.phtml/request" />
				
				<hr tal:condition="not: repeat/usergroup/end" />
			</tal:block>
			
			<hr tal:condition="php: (!membershipRequests.isEmpty() || !friendshipRequests.isEmpty()) && !membershipInvitations.isEmpty()" />

			<tal:block repeat="usergroup membershipInvitations">
				<span metal:use-macro="global/singleusergroup.phtml/invitation" />
				
				<hr tal:condition="not: repeat/usergroup/end" />
			</tal:block>
			
			<span tal:condition="php: friendshipRequests.isEmpty() && membershipRequests.isEmpty() && membershipInvitations.isEmpty()" 
				i18n:translate="">You have no open requests!</span>
			
			<div class="clear" />
		</div>
	</div>

</div>