services:
  frontend-image:
    image: ${REGISTRY:-docker.io}/${REPO_OWNER:-ecamp}/ecamp3-frontend:${VERSION:-latest}
    build:
      context: ../
      dockerfile: .docker-hub/frontend/Dockerfile
      # they have to be registered in GitHub under exactly this name in secrets or vars
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-}
        SENTRY_ORG: ${SENTRY_ORG:-}
        SENTRY_FRONTEND_PROJECT: ${SENTRY_FRONTEND_PROJECT:-}
        SENTRY_RELEASE_NAME: ${RELEASE_NAME:-}
  print-image:
    image: ${REGISTRY:-docker.io}/${REPO_OWNER:-ecamp}/ecamp3-print:${VERSION:-latest}
    build:
      context: ../
      dockerfile: .docker-hub/print/Dockerfile
      # they have to be registered in GitHub under exactly this name in secrets or vars
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-}
        SENTRY_ORG: ${SENTRY_ORG:-}
        SENTRY_PRINT_PROJECT: ${SENTRY_PRINT_PROJECT:-}
        SENTRY_RELEASE_NAME: ${RELEASE_NAME:-}
  varnish-image:
    image: ${REGISTRY:-docker.io}/${REPO_OWNER:-ecamp}/ecamp3-varnish:${VERSION:-latest}
    build:
      context: ../
      dockerfile: .docker-hub/varnish/Dockerfile
