services:
  performance-test:
    image: grafana/k6:2.0.0
    volumes:
      - .:/app
    user: ${USER_ID:-1000}
    network_mode: host
    working_dir: /app
    env_file:
      - path: .env
        required: false
    ports:
      - '5665:5665'
