<span metal:use-macro="camp/header.phtml/header" />

<tal:block condition="exists: camp/getOwner">
	<h2>Owner:</h2>
</tal:block>



<h2>Manager:</h2>

<tal:block repeat="usercamp managers">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user usercamp/getUser" tal:omit-tag="" />
</tal:block>
<div class="clear" />



<h2>Leader:</h2>

<tal:block repeat="usercamp leaders">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user usercamp/getUser" tal:omit-tag="" />
</tal:block>
<div class="clear" />



<h2>Guest:</h2>

<tal:block repeat="usercamp guests">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user usercamp/getUser" tal:omit-tag="" />
</tal:block>
<div class="clear" />