<h1>Ecamp-DB</h1>
<br />
<h2>Schema-Tool</h2>
<form style="display: inline" action="<?php echo $this->url('db/default', array('controller' => 'schema', 'action' => 'create')); ?>">
	<input type="submit" value="Create Schema" />
</form>
<form style="display: inline" action="<?php echo $this->url('db/default', array('controller' => 'schema', 'action' => 'update')); ?>">
	<input type="submit" value="Update Schema" />
</form>
<form style="display: inline" action="<?php echo $this->url('db/default', array('controller' => 'schema', 'action' => 'drop')); ?>">
	<input type="submit" value="Drop Schema" />
</form>
<br />
<br />

<h2>Migration</h2>

<br />
<h2>Backup</h2>

<br />
<h2>Repair UId</h2>
<form style="display: inline" action="<?php echo $this->url('db/default', array('controller' => 'maintenance', 'action' => 'repairUid')); ?>">
	<input type="submit" value="Repair Uid" />
</form>