apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
    k8s-app: filebeat
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- include "app.commonSelectorLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat-kubeadm-config
  namespace: kube-system
  labels:
    app: filebeat
    k8s-app: filebeat
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- include "app.commonSelectorLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: filebeat-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
