apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    app: filebeat
    k8s-app: filebeat
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- include "app.commonSelectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
        {{- include "app.commonLabels" . | nindent 8 }}
        {{- include "app.commonSelectorLabels" . | nindent 8 }}
      annotations:
        # This deployment should be restarted whenever either the configmap or the secrets change
        # because the containers depend on environment variables from these places during startup
        checksum/config: {{ include (print $.Template.BasePath "/filebeat/filebeat_config_map.yaml") . | sha256sum }}
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.11.3
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          resources:
            {{- toYaml .Values.filebeat.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: data
              mountPath: /usr/share/filebeat/data
            - name: host-logs
              mountPath: /var/log
              readOnly: true
            - name: container-logs
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: filebeat-config
        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
        - name: host-logs
          hostPath:
            path: /var/log
        - name: container-logs
          hostPath:
            path: /var/lib/docker/containers
