apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    app: filebeat
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- include "app.commonSelectorLabels" . | nindent 4 }}
