<span metal:use-macro="camp/header.phtml/header" />

<tal:block condition="exists: camp/getOwner">
	<h2>Owner:</h2>
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user camp/getOwner" tal:omit-tag="" />
</tal:block>
<div class="clear" />



<h2>Manager:</h2>

<tal:block repeat="user managers">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:omit-tag="" />
</tal:block>
<div class="clear" />



<h2>Leader:</h2>

<tal:block repeat="user leaders">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:omit-tag="" />
</tal:block>
<div class="clear" />



<h2>Guest:</h2>

<tal:block repeat="user guests">
	<span metal:use-macro="global/singleuser.phtml/withavatar" tal:omit-tag="" />
</tal:block>
<div class="clear" />