<?php

namespace Core\Entity\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CoreEntityGroupProxy extends \Core\Entity\Group implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getDescription()
    {
        $this->_load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->_load();
        return parent::setDescription($description);
    }

    public function getParent()
    {
        $this->_load();
        return parent::getParent();
    }

    public function setParent($parent)
    {
        $this->_load();
        return parent::setParent($parent);
    }

    public function getChildren()
    {
        $this->_load();
        return parent::getChildren();
    }

    public function hasChildren()
    {
        $this->_load();
        return parent::hasChildren();
    }

    public function getUserGroups()
    {
        $this->_load();
        return parent::getUserGroups();
    }

    public function getCamps()
    {
        $this->_load();
        return parent::getCamps();
    }

    public function getMembers()
    {
        $this->_load();
        return parent::getMembers();
    }

    public function getPathAsArray()
    {
        $this->_load();
        return parent::getPathAsArray();
    }

    public function getImageData()
    {
        $this->_load();
        return parent::getImageData();
    }

    public function setImageData($data)
    {
        $this->_load();
        return parent::setImageData($data);
    }

    public function getImageMime()
    {
        $this->_load();
        return parent::getImageMime();
    }

    public function setImageMime($mime)
    {
        $this->_load();
        return parent::setImageMime($mime);
    }

    public function delImage()
    {
        $this->_load();
        return parent::delImage();
    }

    public function isManager($user)
    {
        $this->_load();
        return parent::isManager($user);
    }

    public function acceptRequest($request, $manager)
    {
        $this->_load();
        return parent::acceptRequest($request, $manager);
    }

    public function refuseRequest($request, $manager)
    {
        $this->_load();
        return parent::refuseRequest($request, $manager);
    }

    public function PrePersist()
    {
        $this->_load();
        return parent::PrePersist();
    }

    public function PreUpdate()
    {
        $this->_load();
        return parent::PreUpdate();
    }

    public function getUpdatedAt()
    {
        $this->_load();
        return parent::getUpdatedAt();
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'createdAt', 'updatedAt', 'id', 'name', 'parent', 'children', 'description', 'userGroups', 'camps', 'imageMime', 'imageData');
    }
}