<?php $ctx->form->setAction('createcamp'); ?>

<span metal:use-macro="header.phtml/header" />

<div class="span-10">
	<h1>New Camp</h1>

	You are about to create a new personal camp. This is mainly thought for test camps or for camps that don't belong to a user.
	<br/>
	If you like to create a camp that belongs to a group, please choose a group that you are part of 
	(<a tal:attributes="href helper:url(array('action' => 'groups' ))">goto my groups</a>)
	.

	<tal:block content="structure form" />
</div>
