<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210628071907 extends AbstractMigration {
    public function getDescription(): string {
        return '';
    }

    public function up(Schema $schema): void {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('TRUNCATE TABLE activity, camp, content_node, content_type, period, "user" CASCADE');
        $this->addSql('CREATE TABLE abstract_camp_owner (id VARCHAR(16) NOT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, entityType VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5AEFDEBC9D468A55 ON abstract_camp_owner (createTime)');
        $this->addSql('CREATE INDEX IDX_5AEFDEBC55AA53E2 ON abstract_camp_owner (updateTime)');
        $this->addSql('CREATE TABLE abstract_content_node_owner (id VARCHAR(16) NOT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rootContentNodeId VARCHAR(16) DEFAULT NULL, entityType VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8E710AB4F886581C ON abstract_content_node_owner (rootContentNodeId)');
        $this->addSql('CREATE INDEX IDX_8E710AB49D468A55 ON abstract_content_node_owner (createTime)');
        $this->addSql('CREATE INDEX IDX_8E710AB455AA53E2 ON abstract_content_node_owner (updateTime)');
        $this->addSql('CREATE TABLE activity_responsible (id VARCHAR(16) NOT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, activityId VARCHAR(16) NOT NULL, campCollaborationId VARCHAR(16) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_99684FE41335E2FC ON activity_responsible (activityId)');
        $this->addSql('CREATE INDEX IDX_99684FE456778C5C ON activity_responsible (campCollaborationId)');
        $this->addSql('CREATE INDEX IDX_99684FE49D468A55 ON activity_responsible (createTime)');
        $this->addSql('CREATE INDEX IDX_99684FE455AA53E2 ON activity_responsible (updateTime)');
        $this->addSql('CREATE UNIQUE INDEX activity_campCollaboration_unique ON activity_responsible (activityId, campCollaborationId)');
        $this->addSql('CREATE TABLE camp_collaboration (id VARCHAR(16) NOT NULL, inviteEmail TEXT DEFAULT NULL, inviteKey VARCHAR(64) DEFAULT NULL, status VARCHAR(16) NOT NULL, role VARCHAR(16) NOT NULL, collaborationAcceptedBy TEXT DEFAULT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, userId VARCHAR(16) DEFAULT NULL, campId VARCHAR(16) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C93898A64B64DCC ON camp_collaboration (userId)');
        $this->addSql('CREATE INDEX IDX_C93898A6D299429 ON camp_collaboration (campId)');
        $this->addSql('CREATE INDEX IDX_C93898A9D468A55 ON camp_collaboration (createTime)');
        $this->addSql('CREATE INDEX IDX_C93898A55AA53E2 ON camp_collaboration (updateTime)');
        $this->addSql('CREATE UNIQUE INDEX inviteKey_unique ON camp_collaboration (inviteKey)');
        $this->addSql('CREATE TABLE category (id VARCHAR(16) NOT NULL, categoryPrototypeId VARCHAR(16) DEFAULT NULL, short TEXT NOT NULL, name TEXT NOT NULL, color VARCHAR(8) NOT NULL, numberingStyle VARCHAR(1) NOT NULL, campId VARCHAR(16) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_64C19C16D299429 ON category (campId)');
        $this->addSql('CREATE TABLE category_contenttype (category_id VARCHAR(16) NOT NULL, contenttype_id VARCHAR(16) NOT NULL, PRIMARY KEY(category_id, contenttype_id))');
        $this->addSql('CREATE INDEX IDX_C3C55A4D12469DE2 ON category_contenttype (category_id)');
        $this->addSql('CREATE INDEX IDX_C3C55A4D54491BBC ON category_contenttype (contenttype_id)');
        $this->addSql('CREATE TABLE day (id VARCHAR(16) NOT NULL, dayOffset INT NOT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, periodId VARCHAR(16) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E5A0299085CB41E9 ON day (periodId)');
        $this->addSql('CREATE INDEX IDX_E5A029909D468A55 ON day (createTime)');
        $this->addSql('CREATE INDEX IDX_E5A0299055AA53E2 ON day (updateTime)');
        $this->addSql('CREATE UNIQUE INDEX offset_period_idx ON day (periodId, dayOffset)');
        $this->addSql('CREATE TABLE day_responsible (id VARCHAR(16) NOT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dayId VARCHAR(16) NOT NULL, campCollaborationId VARCHAR(16) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_81AC6A2D194EB424 ON day_responsible (dayId)');
        $this->addSql('CREATE INDEX IDX_81AC6A2D56778C5C ON day_responsible (campCollaborationId)');
        $this->addSql('CREATE INDEX IDX_81AC6A2D9D468A55 ON day_responsible (createTime)');
        $this->addSql('CREATE INDEX IDX_81AC6A2D55AA53E2 ON day_responsible (updateTime)');
        $this->addSql('CREATE TABLE material_item (id VARCHAR(16) NOT NULL, article TEXT NOT NULL, quantity DOUBLE PRECISION DEFAULT NULL, unit TEXT DEFAULT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, materialListId VARCHAR(16) NOT NULL, periodId VARCHAR(16) DEFAULT NULL, contentNodeId VARCHAR(16) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4B73482BC0B3A0A9 ON material_item (materialListId)');
        $this->addSql('CREATE INDEX IDX_4B73482B85CB41E9 ON material_item (periodId)');
        $this->addSql('CREATE INDEX IDX_4B73482B6F35AAFF ON material_item (contentNodeId)');
        $this->addSql('CREATE INDEX IDX_4B73482B9D468A55 ON material_item (createTime)');
        $this->addSql('CREATE INDEX IDX_4B73482B55AA53E2 ON material_item (updateTime)');
        $this->addSql('CREATE TABLE material_list (id VARCHAR(16) NOT NULL, materialListPrototypeId VARCHAR(16) DEFAULT NULL, name TEXT NOT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, campId VARCHAR(16) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_10A0952D6D299429 ON material_list (campId)');
        $this->addSql('CREATE INDEX IDX_10A0952D9D468A55 ON material_list (createTime)');
        $this->addSql('CREATE INDEX IDX_10A0952D55AA53E2 ON material_list (updateTime)');
        $this->addSql('CREATE TABLE organization (id VARCHAR(16) NOT NULL, name TEXT NOT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C1EE637C9D468A55 ON organization (createTime)');
        $this->addSql('CREATE INDEX IDX_C1EE637C55AA53E2 ON organization (updateTime)');
        $this->addSql('CREATE TABLE schedule_entry (id VARCHAR(16) NOT NULL, periodOffset INT NOT NULL, length INT NOT NULL, "left" DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, periodId VARCHAR(16) NOT NULL, activityId VARCHAR(16) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D7785D2C85CB41E9 ON schedule_entry (periodId)');
        $this->addSql('CREATE INDEX IDX_D7785D2C1335E2FC ON schedule_entry (activityId)');
        $this->addSql('CREATE INDEX IDX_D7785D2C9D468A55 ON schedule_entry (createTime)');
        $this->addSql('CREATE INDEX IDX_D7785D2C55AA53E2 ON schedule_entry (updateTime)');
        $this->addSql('ALTER TABLE abstract_content_node_owner ADD CONSTRAINT FK_8E710AB4F886581C FOREIGN KEY (rootContentNodeId) REFERENCES content_node (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activity_responsible ADD CONSTRAINT FK_99684FE41335E2FC FOREIGN KEY (activityId) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activity_responsible ADD CONSTRAINT FK_99684FE456778C5C FOREIGN KEY (campCollaborationId) REFERENCES camp_collaboration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE camp_collaboration ADD CONSTRAINT FK_C93898A64B64DCC FOREIGN KEY (userId) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE camp_collaboration ADD CONSTRAINT FK_C93898A6D299429 FOREIGN KEY (campId) REFERENCES camp (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C16D299429 FOREIGN KEY (campId) REFERENCES camp (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1BF396750 FOREIGN KEY (id) REFERENCES abstract_content_node_owner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category_contenttype ADD CONSTRAINT FK_C3C55A4D12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category_contenttype ADD CONSTRAINT FK_C3C55A4D54491BBC FOREIGN KEY (contenttype_id) REFERENCES content_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE day ADD CONSTRAINT FK_E5A0299085CB41E9 FOREIGN KEY (periodId) REFERENCES period (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE day_responsible ADD CONSTRAINT FK_81AC6A2D194EB424 FOREIGN KEY (dayId) REFERENCES day (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE day_responsible ADD CONSTRAINT FK_81AC6A2D56778C5C FOREIGN KEY (campCollaborationId) REFERENCES camp_collaboration (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material_item ADD CONSTRAINT FK_4B73482BC0B3A0A9 FOREIGN KEY (materialListId) REFERENCES material_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material_item ADD CONSTRAINT FK_4B73482B85CB41E9 FOREIGN KEY (periodId) REFERENCES period (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material_item ADD CONSTRAINT FK_4B73482B6F35AAFF FOREIGN KEY (contentNodeId) REFERENCES content_node (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE material_list ADD CONSTRAINT FK_10A0952D6D299429 FOREIGN KEY (campId) REFERENCES camp (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule_entry ADD CONSTRAINT FK_D7785D2C85CB41E9 FOREIGN KEY (periodId) REFERENCES period (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE schedule_entry ADD CONSTRAINT FK_D7785D2C1335E2FC FOREIGN KEY (activityId) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT fk_ac74095a77075abb');
        $this->addSql('DROP INDEX idx_ac74095abbf8cfda');
        $this->addSql('DROP INDEX idx_ac74095aee35052c');
        $this->addSql('DROP INDEX idx_ac74095a77075abb');
        $this->addSql('ALTER TABLE activity ADD categoryId VARCHAR(16) NOT NULL');
        $this->addSql('ALTER TABLE activity DROP create_time');
        $this->addSql('ALTER TABLE activity DROP update_time');
        $this->addSql('ALTER TABLE activity RENAME COLUMN camp_id TO campId');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A6D299429 FOREIGN KEY (campId) REFERENCES camp (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A9C370B71 FOREIGN KEY (categoryId) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095ABF396750 FOREIGN KEY (id) REFERENCES abstract_content_node_owner (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_AC74095A6D299429 ON activity (campId)');
        $this->addSql('CREATE INDEX IDX_AC74095A9C370B71 ON activity (categoryId)');
        $this->addSql('ALTER TABLE camp DROP CONSTRAINT fk_c194423061220ea6');
        $this->addSql('ALTER TABLE camp DROP CONSTRAINT fk_c19442307e3c61f9');
        $this->addSql('DROP INDEX idx_c19442307e3c61f9');
        $this->addSql('DROP INDEX idx_c1944230bbf8cfda');
        $this->addSql('DROP INDEX idx_c194423061220ea6');
        $this->addSql('DROP INDEX idx_c1944230ee35052c');
        $this->addSql('ALTER TABLE camp ADD addressName TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE camp ADD addressStreet TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE camp ADD addressZipcode TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE camp ADD addressCity TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE camp ADD createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE camp ADD updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE camp ADD creatorId VARCHAR(16) NOT NULL');
        $this->addSql('ALTER TABLE camp ADD ownerId VARCHAR(16) NOT NULL');
        $this->addSql('ALTER TABLE camp DROP creator_id');
        $this->addSql('ALTER TABLE camp DROP owner_id');
        $this->addSql('ALTER TABLE camp DROP address_name');
        $this->addSql('ALTER TABLE camp DROP address_street');
        $this->addSql('ALTER TABLE camp DROP address_zipcode');
        $this->addSql('ALTER TABLE camp DROP address_city');
        $this->addSql('ALTER TABLE camp DROP create_time');
        $this->addSql('ALTER TABLE camp DROP update_time');
        $this->addSql('ALTER TABLE camp RENAME COLUMN camp_prototype_id TO campPrototypeId');
        $this->addSql('ALTER TABLE camp RENAME COLUMN is_prototype TO isPrototype');
        $this->addSql('ALTER TABLE camp ADD CONSTRAINT FK_C194423024B2CCF6 FOREIGN KEY (creatorId) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE camp ADD CONSTRAINT FK_C1944230E05EFD25 FOREIGN KEY (ownerId) REFERENCES abstract_camp_owner (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_C194423024B2CCF6 ON camp (creatorId)');
        $this->addSql('CREATE INDEX IDX_C1944230E05EFD25 ON camp (ownerId)');
        $this->addSql('CREATE INDEX IDX_C19442309D468A55 ON camp (createTime)');
        $this->addSql('CREATE INDEX IDX_C194423055AA53E2 ON camp (updateTime)');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT fk_481d05807e3c61f9');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT fk_481d058079066886');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT fk_481d0580727aca70');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT fk_481d05801a445520');
        $this->addSql('DROP INDEX idx_481d05801a445520');
        $this->addSql('DROP INDEX idx_481d0580727aca70');
        $this->addSql('DROP INDEX idx_481d0580bbf8cfda');
        $this->addSql('DROP INDEX idx_481d0580ee35052c');
        $this->addSql('DROP INDEX idx_481d058079066886');
        $this->addSql('DROP INDEX uniq_481d05807e3c61f9');
        $this->addSql('ALTER TABLE content_node ADD createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_node ADD updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_node ADD rootId VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE content_node ADD parentId VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE content_node DROP owner_id');
        $this->addSql('ALTER TABLE content_node DROP root_id');
        $this->addSql('ALTER TABLE content_node DROP parent_id');
        $this->addSql('ALTER TABLE content_node DROP create_time');
        $this->addSql('ALTER TABLE content_node DROP update_time');
        $this->addSql('ALTER TABLE content_node RENAME COLUMN json_config TO jsonConfig');
        $this->addSql('ALTER TABLE content_node RENAME COLUMN instance_name TO instanceName');
        $this->addSql('ALTER TABLE content_node RENAME COLUMN content_type_id TO contentTypeId');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D0580B7939B21 FOREIGN KEY (rootId) REFERENCES content_node (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D058010EE4CEE FOREIGN KEY (parentId) REFERENCES content_node (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT FK_481D0580FDA329E8 FOREIGN KEY (contentTypeId) REFERENCES content_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_481D0580B7939B21 ON content_node (rootId)');
        $this->addSql('CREATE INDEX IDX_481D058010EE4CEE ON content_node (parentId)');
        $this->addSql('CREATE INDEX IDX_481D0580FDA329E8 ON content_node (contentTypeId)');
        $this->addSql('CREATE INDEX IDX_481D05809D468A55 ON content_node (createTime)');
        $this->addSql('CREATE INDEX IDX_481D058055AA53E2 ON content_node (updateTime)');
        $this->addSql('DROP INDEX idx_41bcbaecee35052c');
        $this->addSql('DROP INDEX idx_41bcbaecbbf8cfda');
        $this->addSql('ALTER TABLE content_type ADD createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_type ADD updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_type DROP create_time');
        $this->addSql('ALTER TABLE content_type DROP update_time');
        $this->addSql('ALTER TABLE content_type RENAME COLUMN strategy_class TO strategyClass');
        $this->addSql('ALTER TABLE content_type RENAME COLUMN json_config TO jsonConfig');
        $this->addSql('CREATE INDEX IDX_41BCBAEC9D468A55 ON content_type (createTime)');
        $this->addSql('CREATE INDEX IDX_41BCBAEC55AA53E2 ON content_type (updateTime)');
        $this->addSql('ALTER TABLE content_type_singletext DROP CONSTRAINT fk_2db8c52599054664');
        $this->addSql('DROP INDEX idx_2db8c52599054664');
        $this->addSql('DROP INDEX idx_2db8c525bbf8cfda');
        $this->addSql('DROP INDEX idx_2db8c525ee35052c');
        $this->addSql('ALTER TABLE content_type_singletext ADD createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_type_singletext ADD updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_type_singletext DROP content_node_id');
        $this->addSql('ALTER TABLE content_type_singletext DROP create_time');
        $this->addSql('ALTER TABLE content_type_singletext DROP update_time');
        $this->addSql('CREATE INDEX IDX_2DB8C5259D468A55 ON content_type_singletext (createTime)');
        $this->addSql('CREATE INDEX IDX_2DB8C52555AA53E2 ON content_type_singletext (updateTime)');
        $this->addSql('ALTER TABLE period DROP CONSTRAINT fk_c5b81ece77075abb');
        $this->addSql('DROP INDEX idx_c5b81eceee35052c');
        $this->addSql('DROP INDEX idx_c5b81ece77075abb');
        $this->addSql('DROP INDEX idx_c5b81ecebbf8cfda');
        $this->addSql('ALTER TABLE period ADD createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE period ADD updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE period DROP create_time');
        $this->addSql('ALTER TABLE period DROP update_time');
        $this->addSql('ALTER TABLE period RENAME COLUMN camp_id TO campId');
        $this->addSql('ALTER TABLE period ADD CONSTRAINT FK_C5B81ECE6D299429 FOREIGN KEY (campId) REFERENCES camp (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_C5B81ECE6D299429 ON period (campId)');
        $this->addSql('CREATE INDEX IDX_C5B81ECE9D468A55 ON period (createTime)');
        $this->addSql('CREATE INDEX IDX_C5B81ECE55AA53E2 ON period (updateTime)');
        $this->addSql('DROP INDEX idx_8d93d649bbf8cfda');
        $this->addSql('DROP INDEX idx_8d93d649ee35052c');
        $this->addSql('ALTER TABLE "user" ADD createTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD updateTime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE "user" DROP create_time');
        $this->addSql('ALTER TABLE "user" DROP update_time');
        $this->addSql('CREATE INDEX IDX_8D93D6499D468A55 ON "user" (createTime)');
        $this->addSql('CREATE INDEX IDX_8D93D64955AA53E2 ON "user" (updateTime)');
    }

    public function down(Schema $schema): void {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE camp DROP CONSTRAINT FK_C1944230E05EFD25');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095ABF396750');
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1BF396750');
        $this->addSql('ALTER TABLE activity_responsible DROP CONSTRAINT FK_99684FE456778C5C');
        $this->addSql('ALTER TABLE day_responsible DROP CONSTRAINT FK_81AC6A2D56778C5C');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095A9C370B71');
        $this->addSql('ALTER TABLE category_contenttype DROP CONSTRAINT FK_C3C55A4D12469DE2');
        $this->addSql('ALTER TABLE day_responsible DROP CONSTRAINT FK_81AC6A2D194EB424');
        $this->addSql('ALTER TABLE material_item DROP CONSTRAINT FK_4B73482BC0B3A0A9');
        $this->addSql('DROP TABLE abstract_camp_owner');
        $this->addSql('DROP TABLE abstract_content_node_owner');
        $this->addSql('DROP TABLE activity_responsible');
        $this->addSql('DROP TABLE camp_collaboration');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE category_contenttype');
        $this->addSql('DROP TABLE day');
        $this->addSql('DROP TABLE day_responsible');
        $this->addSql('DROP TABLE material_item');
        $this->addSql('DROP TABLE material_list');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE schedule_entry');
        $this->addSql('DROP INDEX IDX_8D93D6499D468A55');
        $this->addSql('DROP INDEX IDX_8D93D64955AA53E2');
        $this->addSql('ALTER TABLE "user" ADD create_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD update_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE "user" DROP createTime');
        $this->addSql('ALTER TABLE "user" DROP updateTime');
        $this->addSql('CREATE INDEX idx_8d93d649bbf8cfda ON "user" (update_time)');
        $this->addSql('CREATE INDEX idx_8d93d649ee35052c ON "user" (create_time)');
        $this->addSql('ALTER TABLE camp DROP CONSTRAINT FK_C194423024B2CCF6');
        $this->addSql('DROP INDEX IDX_C194423024B2CCF6');
        $this->addSql('DROP INDEX IDX_C1944230E05EFD25');
        $this->addSql('DROP INDEX IDX_C19442309D468A55');
        $this->addSql('DROP INDEX IDX_C194423055AA53E2');
        $this->addSql('ALTER TABLE camp ADD creator_id VARCHAR(16) NOT NULL');
        $this->addSql('ALTER TABLE camp ADD owner_id VARCHAR(16) NOT NULL');
        $this->addSql('ALTER TABLE camp ADD address_name TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE camp ADD address_street TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE camp ADD address_zipcode TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE camp ADD address_city TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE camp ADD create_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE camp ADD update_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE camp DROP addressName');
        $this->addSql('ALTER TABLE camp DROP addressStreet');
        $this->addSql('ALTER TABLE camp DROP addressZipcode');
        $this->addSql('ALTER TABLE camp DROP addressCity');
        $this->addSql('ALTER TABLE camp DROP createTime');
        $this->addSql('ALTER TABLE camp DROP updateTime');
        $this->addSql('ALTER TABLE camp DROP creatorId');
        $this->addSql('ALTER TABLE camp DROP ownerId');
        $this->addSql('ALTER TABLE camp RENAME COLUMN isprototype TO is_prototype');
        $this->addSql('ALTER TABLE camp RENAME COLUMN campprototypeid TO camp_prototype_id');
        $this->addSql('ALTER TABLE camp ADD CONSTRAINT fk_c194423061220ea6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE camp ADD CONSTRAINT fk_c19442307e3c61f9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_c19442307e3c61f9 ON camp (owner_id)');
        $this->addSql('CREATE INDEX idx_c1944230bbf8cfda ON camp (update_time)');
        $this->addSql('CREATE INDEX idx_c194423061220ea6 ON camp (creator_id)');
        $this->addSql('CREATE INDEX idx_c1944230ee35052c ON camp (create_time)');
        $this->addSql('DROP INDEX IDX_2DB8C5259D468A55');
        $this->addSql('DROP INDEX IDX_2DB8C52555AA53E2');
        $this->addSql('ALTER TABLE content_type_singletext ADD content_node_id VARCHAR(16) NOT NULL');
        $this->addSql('ALTER TABLE content_type_singletext ADD create_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_type_singletext ADD update_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_type_singletext DROP createTime');
        $this->addSql('ALTER TABLE content_type_singletext DROP updateTime');
        $this->addSql('ALTER TABLE content_type_singletext ADD CONSTRAINT fk_2db8c52599054664 FOREIGN KEY (content_node_id) REFERENCES content_node (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_2db8c52599054664 ON content_type_singletext (content_node_id)');
        $this->addSql('CREATE INDEX idx_2db8c525bbf8cfda ON content_type_singletext (update_time)');
        $this->addSql('CREATE INDEX idx_2db8c525ee35052c ON content_type_singletext (create_time)');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095A6D299429');
        $this->addSql('DROP INDEX IDX_AC74095A6D299429');
        $this->addSql('DROP INDEX IDX_AC74095A9C370B71');
        $this->addSql('ALTER TABLE activity ADD camp_id VARCHAR(16) NOT NULL');
        $this->addSql('ALTER TABLE activity ADD create_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE activity ADD update_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE activity DROP campId');
        $this->addSql('ALTER TABLE activity DROP categoryId');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT fk_ac74095a77075abb FOREIGN KEY (camp_id) REFERENCES camp (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_ac74095abbf8cfda ON activity (update_time)');
        $this->addSql('CREATE INDEX idx_ac74095aee35052c ON activity (create_time)');
        $this->addSql('CREATE INDEX idx_ac74095a77075abb ON activity (camp_id)');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D0580B7939B21');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D058010EE4CEE');
        $this->addSql('ALTER TABLE content_node DROP CONSTRAINT FK_481D0580FDA329E8');
        $this->addSql('DROP INDEX IDX_481D0580B7939B21');
        $this->addSql('DROP INDEX IDX_481D058010EE4CEE');
        $this->addSql('DROP INDEX IDX_481D0580FDA329E8');
        $this->addSql('DROP INDEX IDX_481D05809D468A55');
        $this->addSql('DROP INDEX IDX_481D058055AA53E2');
        $this->addSql('ALTER TABLE content_node ADD owner_id VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE content_node ADD root_id VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE content_node ADD parent_id VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE content_node ADD create_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_node ADD update_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_node DROP createTime');
        $this->addSql('ALTER TABLE content_node DROP updateTime');
        $this->addSql('ALTER TABLE content_node DROP rootId');
        $this->addSql('ALTER TABLE content_node DROP parentId');
        $this->addSql('ALTER TABLE content_node RENAME COLUMN contenttypeid TO content_type_id');
        $this->addSql('ALTER TABLE content_node RENAME COLUMN jsonconfig TO json_config');
        $this->addSql('ALTER TABLE content_node RENAME COLUMN instancename TO instance_name');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT fk_481d05807e3c61f9 FOREIGN KEY (owner_id) REFERENCES activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT fk_481d058079066886 FOREIGN KEY (root_id) REFERENCES content_node (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT fk_481d0580727aca70 FOREIGN KEY (parent_id) REFERENCES content_node (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE content_node ADD CONSTRAINT fk_481d05801a445520 FOREIGN KEY (content_type_id) REFERENCES content_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_481d05801a445520 ON content_node (content_type_id)');
        $this->addSql('CREATE INDEX idx_481d0580727aca70 ON content_node (parent_id)');
        $this->addSql('CREATE INDEX idx_481d0580bbf8cfda ON content_node (update_time)');
        $this->addSql('CREATE INDEX idx_481d0580ee35052c ON content_node (create_time)');
        $this->addSql('CREATE INDEX idx_481d058079066886 ON content_node (root_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_481d05807e3c61f9 ON content_node (owner_id)');
        $this->addSql('DROP INDEX IDX_41BCBAEC9D468A55');
        $this->addSql('DROP INDEX IDX_41BCBAEC55AA53E2');
        $this->addSql('ALTER TABLE content_type ADD create_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_type ADD update_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE content_type DROP createTime');
        $this->addSql('ALTER TABLE content_type DROP updateTime');
        $this->addSql('ALTER TABLE content_type RENAME COLUMN strategyclass TO strategy_class');
        $this->addSql('ALTER TABLE content_type RENAME COLUMN jsonconfig TO json_config');
        $this->addSql('CREATE INDEX idx_41bcbaecee35052c ON content_type (create_time)');
        $this->addSql('CREATE INDEX idx_41bcbaecbbf8cfda ON content_type (update_time)');
        $this->addSql('ALTER TABLE period DROP CONSTRAINT FK_C5B81ECE6D299429');
        $this->addSql('DROP INDEX IDX_C5B81ECE6D299429');
        $this->addSql('DROP INDEX IDX_C5B81ECE9D468A55');
        $this->addSql('DROP INDEX IDX_C5B81ECE55AA53E2');
        $this->addSql('ALTER TABLE period ADD create_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE period ADD update_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE period DROP createTime');
        $this->addSql('ALTER TABLE period DROP updateTime');
        $this->addSql('ALTER TABLE period RENAME COLUMN campid TO camp_id');
        $this->addSql('ALTER TABLE period ADD CONSTRAINT fk_c5b81ece77075abb FOREIGN KEY (camp_id) REFERENCES camp (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_c5b81eceee35052c ON period (create_time)');
        $this->addSql('CREATE INDEX idx_c5b81ece77075abb ON period (camp_id)');
        $this->addSql('CREATE INDEX idx_c5b81ecebbf8cfda ON period (update_time)');
    }
}
