fluent-operator:
  containerRuntime: containerd
  operator: 
    annotations: 
      trigger-recreate: ${RANDOM_STRING}
    container: 
      tag: 3.3.0
  fluentbit:
    enable: true
    input:
      tail:
        enable: true
      systemd:
        enable: false
    filter:
      kubernetes:
        labels: true
        annotations: true
    output:
      stdout: 
        # enable to debug fluentbit
        enable: false
  fluentd:
    watchedNamespaces:
      - default
      - ingress-nginx
    envVars: 
      - name: TRIGGER_FLUENTD_RECREATE
        value: ${RANDOM_STRING}
    enable: true

fluentd:
  output:
    elasticsearch:
      enable: true
      scheme: http
      host: "elasticsearch.ecamp3-logging.svc.cluster.local"
      port: 9200
      index: "kubernetes"
      suppressTypeName: true

elastic:
  version: 8.13.2

elasticsearch:
  elasticNode:
    resources:
      requests:
        memory: ${ELASTIC_NODE_REQUESTS_MEMORY}
      limits:
        memory: ${ELASTIC_NODE_LIMITS_MEMORY}
  persistence:
    storageClassName: do-block-storage
    resources:
      requests:
        storage: ${ELASTIC_NODE_STORAGE_SIZE}
  removeOldIndexes:
    maxIndexAge: ${ELASTIC_NODE_MAX_INDEX_AGE}
    image: node:22.15.0

kibana:
  name: kibana
  version:
  resources:
    requests:
      memory: 500Mi
    limits:
      memory: 1Gi
