<h1>Ecamp-Core</h1>
<hr />
<h2>Services</h2>

<form style="display: inline" action="<?php echo $this->url('core/default', array('controller' => 'index', 'action' => 'createServiceConfig')); ?>">
	<input type="submit" value="Create Service-Config" />
</form>

<hr />
<h2>Repositories</h2>

<form style="display: inline" action="<?php echo $this->url('core/default', array('controller' => 'index', 'action' => 'createRepoConfig')); ?>">
	<input type="submit" value="Create Repo-Config" />
</form>
