services:
  restore-backup:
    build:
      context: ../db-backup-restore-image
      dockerfile: Dockerfile
    volumes:
      - ./restore-backup.sh:/restore-backup.sh
      - ./update-support-email.sh:/update-support-email.sh
    command:
      - sh
      - "-x"
      - /restore-backup.sh
    env_file: .env
    network_mode: host
