<span metal:use-macro="camp/header.phtml/header" />

<div class="span-24 last">
    <h2 tal:content="event/getTitle">All Events</h2>
	<a class="button" tal:attributes="href helper:campurl(camp, array('action' => 'show', 'id' => event.getId() ), 'camp+id')">
		Switch to guest view
	</a>
	
	<div class="clear" />
	
	<div class="span-10" id="left">
		<div tal:content="structure container/left" />
	</div>
	
	<div class="span-10" id="right">
		<div tal:content="structure container/right" />
	</div>
	
</div>
