<span metal:use-macro="camp/header.phtml/header" />

<div class="span-24 last">
    <h2 tal:content="event/getTitle">All Events</h2>
	<a class="button" tal:attributes="href helper:campurl(camp, array('action' => 'show', 'id' => event.getId() ), 'camp+id')">
		Switch to guest view
	</a>
	
	<a class="button" tal:attributes="href helper:campurl(camp, array('action' => 'print', 'id' => event.getId() ), 'camp+id')">
		Print preview
	</a>
	
	<div class="clear" />
	
	<div metal:use-macro="${renderEvent/getTemplate/getFilename}" />
	
</div>
