<span metal:use-macro="camp/header.phtml/header" />

<div class="span-24 last">
    <h2>All Events</h2>

	<p>
		<a tal:attributes="href helper:campurl(camp, array('action' => 'create'))">New Random Event</a>
	</p>

	<div class="span-12">
		<table>
			<tr tal:repeat="event camp/getEvents">
				<td><a tal:attributes="href helper:campurl(camp, array('action' => 'show', 'id' => event.getId() ), 'camp+id')" tal:content="event/getTitle" /></td>
				<td>
					<a class="button negative" tal:attributes="href helper:campurl(camp, array('action' => 'delete', 'id' => event.getId() ), 'camp+id')" i18n:translate="">
						delete
					</a>
				</td>
			</tr>
		</table>
	</div>
</div>
