apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-apitoken-secret
  labels:
    {{ include "app.commonLabels" . | nindent 4 }}
    {{ include "app.commonSelectorLabels" . | nindent 4 }}
stringData:
  apiKey: {{ .Values.apiToken | quote }}
