
<!-- <form id="plugin" method="post" tal:attributes="action php:this.thisurl(array('controller' => 'event', 'action' => 'plugin', 'group' => group.getId(), 'camp' => camp.getId(), 'id' => plugin.getId()), 'group+camp+id')" > -->
<form id="plugin" method="post" tal:attributes="action php:this.pluginurl( plugin )" >
	<input type="hidden" name="pluginaction" value="save" />
	
	<input type="text" name="text" tal:attributes="value header/getText" />
	<input type="submit" value="Save" />
</form>


<script type="text/javascript"> 

	function processJson(data) { 
		// 'data' is the json object returned from the server 
		alert(data.message); 
	}
	
	$(document).ready(function() { 
		$('#plugin').ajaxForm({ 
			// dataType identifies the expected content type of the server response 
			dataType:  'json', 
	 
			// success identifies the function to invoke when the server response 
			// has been received 
			success:   processJson 
		});
	});	
	
	
	
</script> 