{
 "title": "eCamp3",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Camps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anzahl aktive Perioden",
   "type": "timeseries",
   "description": "Zeigt pro Tag, wie viele Perioden am laufen sind",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT day\n,      (\n          select count(1) \n          from camp c\n          join period p on p.campid = c.id\n          where p.start <= day and p.end > day\n        )\nfrom generate_series(now(), now() + interval '720' day, '1d'::interval) day"
    }
   ]
  },
  {
   "title": "Sommerlager 2023",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false\nand exists (\n  select 1\n  from  period p\n  where p.campid = c.id\n  and   p.end >  TO_DATE('20230601','YYYYMMDD')\n  and   p.start <  TO_DATE('20230831','YYYYMMDD')\n)"
    }
   ]
  },
  {
   "title": "Aktuell im Lager",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false\nand exists (\n  select 1\n  from period p\n  where p.campid = c.id\n  and p.start <= now() \n  and p.end > now()\n)"
    }
   ]
  },
  {
   "title": "Anzahl erstellte Camps pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', c.createtime), count(1) \nfrom camp c\nwhere c.isprototype=false \ngroup by date_trunc('day', c.createtime)\norder by date_trunc('day', c.createtime)\n"
    }
   ]
  },
  {
   "title": "Nicht abgeschlossene Lager",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false\nand exists (\n  select 1\n  from period p\n  where p.campid = c.id\n  and now() < p.end\n)"
    }
   ]
  },
  {
   "title": "Vergangen",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false\nand not exists (\n  select 1 \n  from  period p \n  where p.campid = c.id\n  and   p.end > now()\n)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false"
    }
   ]
  },
  { "title": "User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "New Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', u.createtime), count(1) \nfrom \"user\"  u\ngroup by date_trunc('day', u.createtime)\norder by date_trunc('day', u.createtime)"
    }
   ]
  },
  {
   "title": "New Users (last 7 days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select u.state, count(1)\nfrom \"user\" u\nwhere u.createtime > now() - interval '7 day'\ngroup by u.state"
    }
   ]
  },
  {
   "title": "Anzahl User",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select u.state, count(1)\nfrom \"user\" u\ngroup by u.state  "
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{server=\"srv0\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Exceeding Latency 500ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{server=\"srv0\"}[5m])) by (code)\n-\nsum(rate(caddy_http_request_duration_seconds_bucket{le=\"0.5\", server=\"srv0\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}