<span metal:define-macro="withavatar" tal:omit-tag="" >
     
	<span  style="" class="span-3">
		<a tal:attributes="href helper:url(array('user' => user.getId()), 'user')">
			<img width="48" height="48" tal:attributes="src helper:url(array('controller' => 'avatar', 'action' => 'user', 'user' => user.getId(), 'size' => 48), 'general')" /><br />
		</a>
		<a tal:attributes="href helper:url(array('user' => user.getId()), 'user')">
			<tal:block content="user/getUsername" />
		</a>
		<br/>
		
		<span metal:define-slot="controls" />
		
		<hr />
	</span>
	
</span>

<span metal:define-macro="big_withemail" tal:omit-tag="" >
	<div class="span-4">
		<img class="left" width="128" height="128" tal:attributes="src helper:url(array('user' => user.getId(), 'controller' => 'avatar', 'action' => 'user', 'size' => 72), 'general')" />
	</div>
	
	<h2 tal:content="user/getUsername">GroupName</h2>
	<h3 tal:content="user/getFullName" />
	<p tal:content="user/getEmail" />
	
</span>