<span metal:define-macro="withavatar" tal:omit-tag="" >
     
	<span  style="height:80px;" class="span-2">
		<a tal:attributes="href helper:url(array('group' => group.getId()), 'group')">
			<img width="48" height="48" tal:attributes="src helper:url(array('action' => 'avatar', 'group' => group.getId(), 'size' => 48), 'group')" /><br />
		</a>
		<a tal:attributes="href helper:url(array('group' => group.getId()), 'group')">
			<tal:block content="group/getName" />
		</a>
		<br/>
		
	</span>
	
</span>