<span metal:define-macro="withavatar" tal:omit-tag="" >
     
	<span  style="height:80px;" class="span-2">
		<a tal:attributes="href helper:url(array('user' => user.getId()), 'user')">
			<img width="48" height="48" tal:attributes="src helper:url(array('action' => 'avatar', 'user' => user.getId(), 'size' => 48), 'user')" /><br />
		</a>
		<a tal:attributes="href helper:url(array('user' => user.getId()), 'user')">
			<tal:block content="user/getUsername" />
		</a>
		<br/>
		
	</span>
	
</span>