<span metal:define-macro="withavatar" tal:omit-tag="" >
     
	<span  style="height:80px;" class="span-2">
		<a tal:attributes="href helper:url(array('group' => group.getId()), 'group')">
			<img width="48" height="48" tal:attributes="src helper:url(array('controller' => 'avatar', 'action'=>'group', 'group' => group.getId(), 'size' => 48), 'general')" /><br />
		</a>
		<a tal:attributes="href helper:url(array('group' => group.getId()), 'group')">
			<tal:block content="group/getName" />
		</a>
		<br/>
		
	</span>
	
</span>


<span metal:define-macro="big" tal:omit-tag="" >
	<div class="span-4">
		<img class="left" width="128" height="128" tal:attributes="src helper:url(array('group' => group.getId(), 'controller' => 'avatar', 'action'=>'group', 'size' => 72), 'general')" />
	</div>
	<h2 tal:content="group/getName">GroupName</h2>
	<h3 tal:content="group/getDescription" />
</span>