<span metal:define-macro="withavatar" tal:omit-tag="" >
     
	<span  style="height:100px;" class="span-2">
		<a tal:attributes="href helper:url(array('group' => usergroup.getGroup().getId()), 'group')">
			<img width="48" height="48" tal:attributes="src helper:url(array('action' => 'avatar', 'group' => usergroup.getGroup().getId(), 'size' => 48), 'group')" /><br />
		</a>
		<a tal:attributes="href helper:url(array('group' => usergroup.getGroup().getId()), 'group')">
			<tal:block content="usergroup/getGroup/getName" />
		</a>
		<tal:block content="usergroup/getRoleName" />
		<br/>
		
	</span>
	
</span>


<span metal:define-macro="member_full" tal:omit-tag="" >
	<div style="height:100px;">
		<span class="span-2">
			<a tal:attributes="href helper:url(array('user' => usergroup.getUser().getId()), 'user')">
				<img width="72" height="72" tal:attributes="src helper:url(array('action' => 'avatar', 'user' => usergroup.getUser().getId(), 'size' => 48), 'user')" /><br />
			</a>
		</span>
		<span class="span-3">
			<a tal:attributes="href helper:url(array('user' => usergroup.getUser().getId()), 'user')">
				<tal:block content="usergroup/getUser/getUsername" />
			</a>
			<br/>
			<tal:block content="usergroup/getUser/getFullName" />
			<br />
			<tal:block content="usergroup/getRoleName" />
		</span>

		<span class="span-2 last" tal:condition="php: me.isManagerOf(group) && me != usergroup.getUser()">
			<a class="button right negative" tal:attributes="href helper:thisurl(array('action' => 'kickout', 'group' => group.getId(), 'user' => usergroup.getUser().getId() ), 'group')">
				kick out
			</a>
		</span>

		<div class="clear" />
	</div>
</span>