traefik:
    providers:
        kubernetesGateway:
            enabled: true
    gatewayClass:
        enabled: true
    gateway:
        enabled: true
        listeners:
            web:
                namespacePolicy:
                    from: All
            websecure:
                port: 8443
                protocol: HTTPS
                namespacePolicy:
                    from: All
                certificateRefs:
                    - name: traefik-certs
    ingressClass:
        enabled: false
    accessLog:
        enabled: true
        format: json
        fields:
            headers:
                defaultMode: keep
