apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: traefik-certs
  labels:
    {{ include "app.commonLabels" . | nindent 4 }}
    {{ include "app.commonSelectorLabels" . | nindent 4 }}
data:
{{ ( include "app.gen-certs" . ) | indent 2 }}
