ingress-nginx:
  fullnameOverride: ingress-nginx
  controller:
    metrics:
      enabled: true
    podAnnotations:
      "prometheus.io/scrape": "true"
      "prometheus.io/port": "10254"
    config:
      log-format-escape-json: true
      log-format-upstream: {"timestamp":"$time_iso8601","requestID":"$req_id","proxyUpstreamName":"$proxy_upstream_name","proxyAlternativeUpstreamName":"$proxy_alternative_upstream_name","upstreamStatus":$upstream_status,"upstreamAddr":"$upstream_addr","httpRequest":{"requestMethod":"$request_method","requestUrl":"$host$request_uri","status":$status,"requestSize":"$request_length","responseSize":"$upstream_response_length","userAgent":"$http_user_agent","remoteIp":"$remote_addr","referer":"$http_referer","request_time_seconds":$upstream_response_time,"protocol":"$server_protocol"}}
