ingress-nginx:
  fullnameOverride: ingress-nginx
  controller:
    service:
      enabled: false
    metrics:
      enabled: true
    podAnnotations:
      "prometheus.io/scrape": "true"
      "prometheus.io/port": "10254"
    config:
      log-format-escape-json: true
      log-format-upstream: |
        {"timestamp":"$time_iso8601","requestID":"$req_id","proxyUpstreamName":"$proxy_upstream_name","proxyAlternativeUpstreamName":"$proxy_alternative_upstream_name","upstreamStatus":$upstream_status,"upstreamAddr":"$upstream_addr","httpRequest":{"requestMethod":"$request_method","requestUrl":"$host$request_uri","status":$status,"requestSize":"$request_length","responseSize":"$upstream_response_length","userAgent":"$http_user_agent","remoteIp":"$remote_addr","referer":"$http_referer","request_time_seconds":$upstream_response_time,"protocol":"$server_protocol"}}
f5-nginx-ingress:
  controller:
    ingressClass:
      name: f5-nginx-ingress
    kind: deployment
    nginxplus: false
    service:
      create: false
    selectorLabels:
      deployment: f5-nginx-ingress
    podAnnotations:
      "prometheus.io/scrape": "true"
      "prometheus.io/port": "9113"
    prometheus:
      create: true
      port: 9113
    config:
      entries:
        log-format: |
          {"timestamp":"$time_iso8601","requestID":"$request_id","proxyUpstreamName":"$upstream_addr","upstreamStatus":$upstream_status,"upstreamAddr":"$upstream_addr","httpRequest":{"requestMethod":"$request_method","requestUrl":"$host$request_uri","status":$status,"requestSize":"$request_length","responseSize":"$upstream_response_length","userAgent":"$http_user_agent","remoteIp":"$remote_addr","referer":"$http_referer","request_time_seconds":$upstream_response_time,"protocol":"$server_protocol"}}
