<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return [
    'Zend\Session',
    'Zend\\Cache',
    'Zend\\Form',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Session',
	'Zend\\Validator',
	'Phpro\\DoctrineHydrationModule',
    'ZF\\Apigility',
	'ZF\\Apigility\\Documentation',
	'ZF\\Apigility\\Doctrine\\Server',
	'ZF\\ApiProblem',
	'ZF\\Configuration',
	'ZF\Doctrine\Hydrator',
    'ZF\\OAuth2',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'DoctrineModule',
    'DoctrineORMModule',
	'ZF\Doctrine\QueryBuilder',
	
    'EcampLib',
    'EcampCore',
	'Application',
    'EcampApi',
];
