log_format  body  $decoded_body;
access_log /dev/stdout body;
client_body_buffer_size 10k;
client_max_body_size 10k;
server {
  set $decoded_body "";
  listen       3000;
  server_name  localhost;
  location / {
    root   /app;
    index  index.html;
    try_files $uri $uri/ /index.html;
  }
  location /log {
    lua_need_request_body on;
     access_by_lua_block {
        ngx.req.read_body()
        local body = ngx.req.get_body_data()
        
        if body then
            local decoded = ngx.unescape_uri(body)
            ngx.var.decoded_body = decoded
        end
    }
      
    content_by_lua_block {
      ngx.say("Body logged")
    }
  }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
