
<tal:block condition="loginPMod">
	<h2>Currently Authenticated as:</h2>

	<p>

	<tal:block i18n:translate="">Hello World</tal:block><br />
	<tal:block i18n:translate="">You are <span i18n:name="name" tal:replace="loginPMod/Login/GetLogin"/></tal:block>
	</p>
	
</tal:block>


<h2>Login as:</h2>
<table>
	<tr tal:repeat="login logins">
		<td><a tal:attributes="href login/GetLoginLink">Login</a></td>
		<td>::</td>
		<td tal:content="login/Login/GetLogin" />
	</tr>
</table>

