<!DOCTYPE html>
<html>
	<head>
		<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<tal:block content="structure headTitle" />
		<tal:block content="structure headMeta"  />
		<tal:block content="structure headLink"  />

	</head>

	<body>
		<div class="topheader">
		</div>

		<div class="container">
			<header>
				<h1>eCamp v3</h1>
				<hr />
				<h2 class="alt">This sentence is here for nothing.</h2>
				<hr />

				<nav>
					<ul>
						<li><a href="/">This Index</a></li>
						<li><a href="/login">Login</a></li>
						<li><a href="/login/logout">Logout</a></li>
						<li><a href="/camp">Camps</a></li>
						<li><a href="/doctrine">Doctrine</a></li>
						<li><a href="/zend">Initial Zend Index</a></li>
						<li><a href="/error">An error example</a></li>
					</ul>

				</nav>

				<hr />
			</header>
		
			<section>
				<tal:block content="structure viewContent" />
			</section>



		</div>
	
		<footer>
			<nav>
				<ul>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
					<li><a href="#">Impressum</a></li>
				</ul>
			</nav>
		</footer>
	</body>
</html>