apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql/%s?serverVersion=13&charset=utf8" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  php-jwt-passphrase: {{ .Values.php.jwt.passphrase | default (randAlphaNum 40) | b64enc | quote }}
  jwt-public-key: {{ .Values.php.jwt.publicKey | default "" | b64enc | quote }}
  jwt-private-key: {{ .Values.php.jwt.privateKey | default "" | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.mercure.jwtSecret | default (randAlphaNum 40) | b64enc | quote }}
  {{- if .Values.mail.dummyEnabled }}
  mailer-dsn: {{ .Values.mail.dsn | default (printf "smtp://%s:1025" (include "mail.name" .)) | b64enc | quote }}
  {{- else if .Values.mail.dsn }}
  mailer-dsn: {{ .Values.mail.dsn | b64enc | quote }}
  {{- end }}
  recaptcha-secret: {{ .Values.recaptcha.secret | default "" | b64enc | quote }}
