apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "api.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql/%s?serverVersion=13&charset=utf8" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  php-jwt-passphrase: {{ .Values.php.jwt.passphrase | default (randAlphaNum 40) | b64enc | quote }}
  jwt-public-key: {{ .Values.php.jwt.publicKey | default "" | b64enc | quote }}
  jwt-private-key: {{ .Values.php.jwt.privateKey | default "" | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.mercure.jwtSecret | default (randAlphaNum 40) | b64enc | quote }}
  {{- if .Values.php.oauth.google.clientId }}
  oauth-google-client-id: {{ .Values.php.oauth.google.clientId | default "" | b64enc | quote }}
  oauth-google-client-secret: {{ .Values.php.oauth.google.clientSecret | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.php.oauth.pbsmidata.clientId }}
  oauth-pbsmidata-client-id: {{ .Values.php.oauth.pbsmidata.clientId | default "" | b64enc | quote }}
  oauth-pbsmidata-client-secret: {{ .Values.php.oauth.pbsmidata.clientSecret | default "" | b64enc | quote }}
  oauth-pbsmidata-base-url: {{ .Values.php.oauth.pbsmidata.baseUrl | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.php.oauth.cevidb.clientId }}
  oauth-cevidb-client-id: {{ .Values.php.oauth.cevidb.clientId | default "" | b64enc | quote }}
  oauth-cevidb-client-secret: {{ .Values.php.oauth.cevidb.clientSecret | default "" | b64enc | quote }}
  oauth-cevidb-base-url: {{ .Values.php.oauth.cevidb.baseUrl | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.mail.dummyEnabled }}
  mailer-dsn: {{ .Values.mail.dsn | default (printf "smtp://%s:1025" (include "mail.name" .)) | b64enc | quote }}
  {{- else if .Values.mail.dsn }}
  mailer-dsn: {{ .Values.mail.dsn | b64enc | quote }}
  {{- end }}
  recaptcha-secret: {{ .Values.recaptcha.secret | default "" | b64enc | quote }}
  coupon-secret: {{ .Values.coupon.secret | default "" | b64enc | quote }}
