{{- if .Values.ingress.enabled -}}
{{- $apiPath := .Values.api.subpath }}
{{- if eq .Values.ingress.className "nginx" }}
{{- $apiPath = printf "%s(/|$)(.*)" $apiPath }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "api.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "ingress.basicAuth.annotations" . | nindent 4 }}
    {{- if eq .Values.ingress.className "f5-nginx-ingress" }}
    nginx.org/rewrites: "serviceName={{ if .Values.apiCache.enabled }}{{ include "apiCache.name" . }}{{ else }}{{ include "api.name" . }}{{ end }} rewrite=/"
    {{- else if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: {{ .Values.api.subpath }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ $.Values.domain | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: {{ $apiPath }}
            pathType: {{ include "ingress.pathType" . }}
            backend:
              service:
                {{- if .Values.apiCache.enabled }}
                name: {{ include "apiCache.name" . }}
                port:
                  number: {{ .Values.apiCache.service.ports.http }}
                {{- else }}
                name: {{ include "api.name" . }}
                port:
                  number: {{ .Values.api.service.port }}
                {{- end }}
{{- end }}
