{{- if .Values.ingress.basicAuth.enabled -}}
{{- $basicAuth := .Values.ingress.basicAuth -}}
{{- $username := $basicAuth.username | required ".Values.ingress.basicAuth.username is required if .Values.ingress.basicAuth.enabled is true" -}}
{{- $password := $basicAuth.password | required ".Values.ingress.basicAuth.password is required if .Values.ingress.basicAuth.enabled is true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingress.basicAuth.secret.name" . | quote }}
type: Opaque
data:
  auth: {{ htpasswd $username $password | b64enc | quote }}
{{- end }}
