{{- if .Values.browserless.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "browserless.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-browserless
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.browserless.image.repository }}:{{ .Values.browserless.image.tag }}"
          imagePullPolicy: {{ .Values.browserless.image.pullPolicy }}
          ports:
            - name: browserless-ws
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /pressure
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /pressure
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}