{{- if .Values.postgresql.backup.schedule }}
{{- $databaseUrl := .Values.postgresql.url | required ".Values.postgresql.url is required." -}}
{{- $s3_endpoint := .Values.postgresql.backup.s3.endpoint | required ".Values.postgresql.backup.s3.endpoint is required." -}}
{{- $s3_bucket := .Values.postgresql.backup.s3.bucket | required ".Values.postgresql.backup.s3.bucket is required." -}}
{{- $s3_accessKeyId := .Values.postgresql.backup.s3.accessKeyId | required ".Values.postgresql.backup.s3.accessKeyId is required." -}}
{{- $s3_accessKey := .Values.postgresql.backup.s3.accessKey | required ".Values.postgresql.backup.s3.accessKey is required." -}}
{{- $encryptionKey := .Values.postgresql.backup.encryptionKey -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbBackupJob.name" . }}
  labels:
    {{- include "dbBackupJob.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ $databaseUrl | b64enc | quote }}
  s3-endpoint: {{ $s3_endpoint | b64enc | quote }}
  s3-bucket: {{ $s3_bucket | b64enc | quote }}
  s3-access-key-id: {{ $s3_accessKeyId | b64enc | quote }}
  s3-access-key: {{ $s3_accessKey | b64enc | quote }}
  {{- if $encryptionKey }}
  encryption-key: {{ $encryptionKey | b64enc | quote }}
  {{- end }}
{{- end }}
