apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.name" . }}
  labels:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: frontend-http
      protocol: TCP
      name: frontend-http
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
