#
# Provides the admin database credentials for the hooks that automatically create and drop the database.
#
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "app.name" . }}-hooks"
  labels:
    {{- include "api.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  admin-database-url: {{ .Values.postgresql.adminUrl | default .Values.postgresql.url | b64enc | quote }}
{{- end }}