#
# Automatically drops the database in an external PostgreSQL when completely uninstalling the chart.
#
{{- if and (not .Values.postgresql.enabled) .Values.postgresql.dropDBOnUninstall }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "app.name" . }}-db-drop"
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "app.name" . }}-post-delete"
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: db-drop-job
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Values.imageTag }}"
          command: ["php", "bin/console", "doctrine:database:drop", "--if-exists", "-f"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: admin-database-url
                  name: {{ include "app.name" . }}-hooks
{{- end }}