{{- if and .Values.mail.dummyEnabled .Values.mail.subpath (not .Values.mail.dsn) }}
{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mail.name" . }}
  labels:
    {{- include "mail.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: api-gateway
  hostnames:
    - {{ .Values.domain | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.mail.subpath }}
      filters:
        {{- if .Values.ingress.basicAuth.enabled }}
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: {{ printf "%s-basic-auth" (include "app.name" .) | quote }}
        {{- end }}
      backendRefs:
        - name: {{ include "mail.name" . }}
          port: {{ .Values.mail.service.port }}
{{- end }}
{{- end }}
