{{- $basicAuth := .Values.ingress.basicAuth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "print.name" . }}
  labels:
    {{- include "print.selectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.print.sentryDsn }}
  sentry-dsn: {{ .Values.print.sentryDsn | b64enc | quote }}
  {{- else}}
  sentry-dsn: ""
  {{- end }}

  {{- if .Values.browserless.enabled }}
  browser-ws-endpoint: {{  printf "ws://%s:%d" (include "browserless.name" .) (.Values.browserless.service.port | int) | b64enc | quote }}
  {{- else if .Values.print.browserWsEndpoint }}
  browser-ws-endpoint: {{ .Values.print.browserWsEndpoint | b64enc | quote }}
  {{- else}}
  browser-ws-endpoint: ""
  {{- end }}
  {{- if and .Values.ingress.enabled .Values.ingress.basicAuth.enabled }}
  basic-auth-token: {{ printf "%s:%s" $basicAuth.username $basicAuth.password | b64enc | b64enc | quote }}
  {{- end }}
