{{- if and .Values.gateway.enabled (.Values.gateway.className | contains "traefik") -}}
{{- if .Values.gateway.basicAuth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "app.name" . }}-basic-auth
  labels:
    {{- include "app.commonSelectorLabels" . | nindent 4 }}
    {{- include "app.commonLabels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "gateway.basicAuth.secret.name" . | quote }}
{{- end }}
{{- end }}
