apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app: kibana
    {{- include "app.commonLabels" . | nindent 4 }}
    {{- include "app.commonSelectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      {{- include "app.commonSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: kibana
        {{- include "app.commonLabels" . | nindent 8 }}
        {{- include "app.commonSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: kibana
          image: "docker.elastic.co/kibana/kibana:{{ .Values.elastic.version }}"
          resources:
            {{- toYaml .Values.elasticsearch.elasticNode.resources | nindent 12 }}
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200
          ports:
            - containerPort: 5601
