<span metal:use-macro="header.phtml/header" />

<div class="span-24 last">
    <h2>All Camps</h2>

	<p>
	<a tal:attributes="href helper:thisurl(array('action' => 'newcamp', 'group' => group.getId()))">NewCamp</a>
	</p>

	<div class="span-12">
		<table>
			<tr tal:repeat="camp group/getCamps">
				<td>
				  <a tal:content="camp/getName" tal:attributes="href helper:url(array('controller'=>'camp', 'group' => group.getId(), 'camp' => camp.getId() ), 'group+camp')" />
				</td>
				<td><tal:block content="camp/getTitle" /></td>
				<td><tal:block content="camp/getRange" /></td>
				<td>
					<a id="edit" class="button" tal:attributes="href helper:thisurl(array('action' => 'editcamp', 'group' => group.getId(), 'id' => camp.getId() ), 'group+id')" i18n:translate="">
						edit
					</a>
					<a id="delete" class="button negative" tal:attributes="href helper:thisurl(array('action' => 'deletecamp', 'group' => group.getId(), 'id' => camp.getId() ), 'group+id')" i18n:translate="">
						delete
					</a>
				</td>
			</tr>
		</table>
	</div>
</div>