<span metal:define-macro="header">
	<div class="group_logo">
		<img width="32" height="32" tal:attributes="src helper:url(array('group' => group.getId(), 'action' => 'avatar', 'size' => 32), 'group')" /><br />
	</div>
	
	<div class="group_header" tal:content="group/getName">GroupName</div>
	<div class="group_breadcrumb">
		
		<span tal:repeat="item group/getPathAsArray">
			<a tal:content="item/getDescription" tal:attributes="href helper:thisurl(array('group' => item.getId() ), 'group')">GroupDescription</a> >>
		</span>
		
		<tal:block content="group/getDescription" />
	</div>

	<nav id="mainnav">
		<tal:block content="structure php: this.navigation().menu().renderMenu(NULL, array('maxDepth' => 0, 'ulClass' => 'left'))" />

		<a id="request_membership" class="button right positive" tal:condition="php: me.canRequestMembership(group)" tal:attributes="href helper:thisurl(array('action' => 'request', 'group' => group.getId() ), 'group')">
			request membership
		</a>

		<a class="button right negative" tal:condition="php: me.isMemberOf(group)" tal:attributes="href helper:thisurl(array('action' => 'leave', 'group' => group.getId() ), 'group')">
			leave this group
		</a>

		<a class="button right negative" tal:condition="php: me.hasOpenRequest(group)" tal:attributes="href helper:thisurl(array('action' => 'leave', 'group' => group.getId() ), 'group')">
			withdraw request
		</a>

		<div class="clear" />
	</nav>


	<tal:block content="structure helper:confirmDialog('request_membership_dialog', 'request_membership', 'Request Membership', 'Do you want to request membership for this group? Your email address will be sent to the group managers.')" />

</span>