<span metal:use-macro="header.phtml/header" />

<div class="span-13">
	<div tal:condition="group/hasChildren">
		<h2>Subgroups</h2>
		<div tal:repeat="subgroup group/getChildren" class="span-3 avatarlist">
			<a tal:attributes="href helper:url(array('group' => subgroup.getId()), 'group')">
				<img tal:attributes="src helper:url(array('group' => subgroup.getId(), 'action' => 'avatar'), 'group')" /><br />
			</a>
			<a tal:attributes="href helper:url(array('group' => subgroup.getId()), 'group')">
				<tal:block content="subgroup/getName" />
			</a>
		</div>
	</div>
	
	<br />
</div>
<div class="span-11 last">

	<div class="bigbox">
		<div class="title">Mitglieder</div>
		<div class="content">blablabla</div>
	</div>

	<div class="bigbox">
		<div class="title">Lager / Kurse</div>
		<div class="content">blablabla</div>
	</div>

</div>