knpu_oauth2_client:
    clients:
        google:
            provider_class: App\OAuth\MockGoogle
            provider_options:
                baseUrl: '%env(MOCK_OAUTH_INTERNAL_BASE_URL)%/google'
                externalBaseUrl: '%env(MOCK_OAUTH_EXTERNAL_BASE_URL)%/google'
        pbsmidata:
            provider_class: App\OAuth\MockHitobito
            provider_options:
                baseUrl: '%env(MOCK_HITOBITO_INTERNAL_BASE_URL)%/pbsmidata'
                externalBaseUrl: '%env(MOCK_OAUTH_EXTERNAL_BASE_URL)%/pbsmidata'
                # todo: check if really needed
                realBaseUrl: '%env(OAUTH_PBSMIDATA_BASE_URL)%'
        pbsmidata_hitobito_api:
            provider_class: App\OAuth\MockHitobito
            provider_options:
                baseUrl: '%env(MOCK_HITOBITO_INTERNAL_BASE_URL)%/pbsmidata'
                externalBaseUrl: '%env(MOCK_OAUTH_EXTERNAL_BASE_URL)%/pbsmidata'
        cevidb:
            provider_class: App\OAuth\MockHitobito
            provider_options:
                baseUrl: '%env(MOCK_HITOBITO_INTERNAL_BASE_URL)%/cevidb'
                externalBaseUrl: '%env(MOCK_OAUTH_EXTERNAL_BASE_URL)%/cevidb'
                realBaseUrl: '%env(OAUTH_CEVIDB_BASE_URL)%'
        jubladb:
            provider_class: App\OAuth\MockHitobito
            provider_options:
                baseUrl: '%env(MOCK_HITOBITO_INTERNAL_BASE_URL)%/jubladb'
                externalBaseUrl: '%env(MOCK_OAUTH_EXTERNAL_BASE_URL)%/jubladb'
                realBaseUrl: '%env(OAUTH_JUBLADB_BASE_URL)%'
