<?php /* All id's should contain the plugin id in order to prevent conflicts */ ?>

	<form id="plugin" method="post" tal:attributes="id php:'plugin'.(plugin.getId()); action php:this.pluginurl( plugin, 'save' )" >
    	<input type="text" id="text" name="text" tal:attributes="value content/getText" />
    	<input type="submit" value="Save" />
    </form>


<script type="text/javascript"> 

	
	
	$(document).ready(function() { 
		$('#plugin<?php echo $ctx->plugin->getId() ?>').ajaxForm({
			// dataType identifies the expected content type of the server response 
			dataType:  'json', 
			xhrFields:{
				withCredentials:true
				},
	 
			// success identifies the function to invoke when the server response 
			// has been received 
			success:   function (data, status) { 
				// 'data' is the json object returned from the server 
				$('#plugin'+data.request.id+' #text').val(data.response.text);
			} 
		});
	});	
	
	
	
</script> 