<span metal:use-macro="camp/header.phtml/header" />

<div class="span-24 last">
    <h2 tal:content="event/getTitle">All Events</h2>
	
	<a class="button" tal:attributes="href helper:campurl(camp, array('action' => 'edit', 'id' => event.getId() ), 'camp+id')">
		Give me write access
	</a>
	
	<div class="clear" />
	
	<div class="span-14">
		<div class="box" tal:repeat="plugin event/getPlugins" tal:content="structure plugin/getStrategyInstance/renderFrontend" />
	</div>
</div>
