
<?php
return array(
	
	'aliases' => array(
		'__repos__.ecampCore_CampRepo' => 'ecampcore.repo.camp',
		'__repos__.ecampCore_CampTypeRepo' => 'ecampcore.repo.camptype',
		'__repos__.ecampCore_DayRepo' => 'ecampcore.repo.day',
		'__repos__.ecampCore_EventRepo' => 'ecampcore.repo.event',
		'__repos__.ecampCore_EventCategoryRepo' => 'ecampcore.repo.eventcategory',
		'__repos__.ecampCore_EventInstanceRepo' => 'ecampcore.repo.eventinstance',
		'__repos__.ecampCore_EventPrototypeRepo' => 'ecampcore.repo.eventprototype',
		'__repos__.ecampCore_EventRespRepo' => 'ecampcore.repo.eventresp',
		'__repos__.ecampCore_EventTemplateRepo' => 'ecampcore.repo.eventtemplate',
		'__repos__.ecampCore_EventTypeRepo' => 'ecampcore.repo.eventtype',
		'__repos__.ecampCore_GroupRepo' => 'ecampcore.repo.group',
		'__repos__.ecampCore_GroupRequestRepo' => 'ecampcore.repo.grouprequest',
		'__repos__.ecampCore_ImageRepo' => 'ecampcore.repo.image',
		'__repos__.ecampCore_LoginRepo' => 'ecampcore.repo.login',
		'__repos__.ecampCore_MediumRepo' => 'ecampcore.repo.medium',
		'__repos__.ecampCore_PeriodRepo' => 'ecampcore.repo.period',
		'__repos__.ecampCore_PluginRepo' => 'ecampcore.repo.plugin',
		'__repos__.ecampCore_PluginInstanceRepo' => 'ecampcore.repo.plugininstance',
		'__repos__.ecampCore_PluginPositionRepo' => 'ecampcore.repo.pluginposition',
		'__repos__.ecampCore_PluginPrototypeRepo' => 'ecampcore.repo.pluginprototype',
		'__repos__.ecampCore_UIdRepo' => 'ecampcore.repo.uid',
		'__repos__.ecampCore_UserRepo' => 'ecampcore.repo.user',
		'__repos__.ecampCore_UserCampRepo' => 'ecampcore.repo.usercamp',
		'__repos__.ecampCore_UserGroupRepo' => 'ecampcore.repo.usergroup',
		'__repos__.ecampCore_UserRelationshipRepo' => 'ecampcore.repo.userrelationship',
	),

	'factories' => array(
		'ecampcore.repo.camp' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Camp'),
		'ecampcore.repo.camptype' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\CampType'),
		'ecampcore.repo.day' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Day'),
		'ecampcore.repo.event' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Event'),
		'ecampcore.repo.eventcategory' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\EventCategory'),
		'ecampcore.repo.eventinstance' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\EventInstance'),
		'ecampcore.repo.eventprototype' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\EventPrototype'),
		'ecampcore.repo.eventresp' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\EventResp'),
		'ecampcore.repo.eventtemplate' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\EventTemplate'),
		'ecampcore.repo.eventtype' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\EventType'),
		'ecampcore.repo.group' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Group'),
		'ecampcore.repo.grouprequest' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\GroupRequest'),
		'ecampcore.repo.image' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Image'),
		'ecampcore.repo.login' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Login'),
		'ecampcore.repo.medium' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Medium'),
		'ecampcore.repo.period' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Period'),
		'ecampcore.repo.plugin' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\Plugin'),
		'ecampcore.repo.plugininstance' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\PluginInstance'),
		'ecampcore.repo.pluginposition' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\PluginPosition'),
		'ecampcore.repo.pluginprototype' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\PluginPrototype'),
		'ecampcore.repo.uid' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\UId'),
		'ecampcore.repo.user' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\User'),
		'ecampcore.repo.usercamp' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\UserCamp'),
		'ecampcore.repo.usergroup' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\UserGroup'),
		'ecampcore.repo.userrelationship' => new EcampCore\RepositoryUtil\RepositoryFactory('EcampCore\Entity\UserRelationship'),
	),
	
);