<?php
return array(
	
	'aliases' => array(
		'__services__.ecampCore_AvatarService' => 'ecampcore.service.avatar',
		'__services__.ecampCore_CampService' => 'ecampcore.service.camp',
		'__services__.ecampCore_ContributionService' => 'ecampcore.service.contribution',
		'__services__.ecampCore_DayService' => 'ecampcore.service.day',
		'__services__.ecampCore_EventInstanceService' => 'ecampcore.service.eventinstance',
		'__services__.ecampCore_EventService' => 'ecampcore.service.event',
		'__services__.ecampCore_GroupService' => 'ecampcore.service.group',
		'__services__.ecampCore_LoginService' => 'ecampcore.service.login',
		'__services__.ecampCore_MembershipService' => 'ecampcore.service.membership',
		'__services__.ecampCore_PeriodService' => 'ecampcore.service.period',
		'__services__.ecampCore_RegisterService' => 'ecampcore.service.register',
		'__services__.ecampCore_RelationshipService' => 'ecampcore.service.relationship',
		'__services__.ecampCore_SearchUserService' => 'ecampcore.service.searchuser',
		'__services__.ecampCore_SupportService' => 'ecampcore.service.support',
		'__services__.ecampCore_UserService' => 'ecampcore.service.user',

		'__internal_services__.ecampCore_AvatarService' => 'ecampcore.internal.service.avatar',
		'__internal_services__.ecampCore_CampService' => 'ecampcore.internal.service.camp',
		'__internal_services__.ecampCore_ContributionService' => 'ecampcore.internal.service.contribution',
		'__internal_services__.ecampCore_DayService' => 'ecampcore.internal.service.day',
		'__internal_services__.ecampCore_EventInstanceService' => 'ecampcore.internal.service.eventinstance',
		'__internal_services__.ecampCore_EventService' => 'ecampcore.internal.service.event',
		'__internal_services__.ecampCore_GroupService' => 'ecampcore.internal.service.group',
		'__internal_services__.ecampCore_LoginService' => 'ecampcore.internal.service.login',
		'__internal_services__.ecampCore_MembershipService' => 'ecampcore.internal.service.membership',
		'__internal_services__.ecampCore_PeriodService' => 'ecampcore.internal.service.period',
		'__internal_services__.ecampCore_RegisterService' => 'ecampcore.internal.service.register',
		'__internal_services__.ecampCore_RelationshipService' => 'ecampcore.internal.service.relationship',
		'__internal_services__.ecampCore_SearchUserService' => 'ecampcore.internal.service.searchuser',
		'__internal_services__.ecampCore_SupportService' => 'ecampcore.internal.service.support',
		'__internal_services__.ecampCore_UserService' => 'ecampcore.internal.service.user',
	),

	'factories' => array(
		'ecampcore.service.avatar' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.avatar'),
		'ecampcore.service.camp' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.camp'),
		'ecampcore.service.contribution' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.contribution'),
		'ecampcore.service.day' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.day'),
		'ecampcore.service.eventinstance' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.eventinstance'),
		'ecampcore.service.event' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.event'),
		'ecampcore.service.group' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.group'),
		'ecampcore.service.login' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.login'),
		'ecampcore.service.membership' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.membership'),
		'ecampcore.service.period' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.period'),
		'ecampcore.service.register' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.register'),
		'ecampcore.service.relationship' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.relationship'),
		'ecampcore.service.searchuser' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.searchuser'),
		'ecampcore.service.support' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.support'),
		'ecampcore.service.user' => new EcampLib\Service\ServiceFactory('ecampcore.internal.service.user'),
	),

    'invokables' => array(
		'ecampcore.internal.service.avatar' => 'EcampCore\Service\AvatarService',
		'ecampcore.internal.service.camp' => 'EcampCore\Service\CampService',
		'ecampcore.internal.service.contribution' => 'EcampCore\Service\ContributionService',
		'ecampcore.internal.service.day' => 'EcampCore\Service\DayService',
		'ecampcore.internal.service.eventinstance' => 'EcampCore\Service\EventInstanceService',
		'ecampcore.internal.service.event' => 'EcampCore\Service\EventService',
		'ecampcore.internal.service.group' => 'EcampCore\Service\GroupService',
		'ecampcore.internal.service.login' => 'EcampCore\Service\LoginService',
		'ecampcore.internal.service.membership' => 'EcampCore\Service\MembershipService',
		'ecampcore.internal.service.period' => 'EcampCore\Service\PeriodService',
		'ecampcore.internal.service.register' => 'EcampCore\Service\RegisterService',
		'ecampcore.internal.service.relationship' => 'EcampCore\Service\RelationshipService',
		'ecampcore.internal.service.searchuser' => 'EcampCore\Service\SearchUserService',
		'ecampcore.internal.service.support' => 'EcampCore\Service\SupportService',
		'ecampcore.internal.service.user' => 'EcampCore\Service\UserService',
    ),
    
);