{
 "title": "eCamp3",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "Camps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anzahl aktive Perioden",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n      COALESCE(campPrototypeId, 'none')\n      WHEN 'f92fe1cd1ae9' THEN 'Basic'\n      WHEN '75b3572a338e' THEN 'J+S Lager DE'\n      WHEN '497f974e7d5d' THEN 'J+S Lager FR'\n      WHEN 'dffcb39cb4fb' THEN 'J+S Kurs DE'\n      WHEN 'fc8417239f9a' THEN 'J+S Kurs FR'\n      WHEN 'none' THEN 'No Prototype'\n      ELSE 'Other camp prototype'\n    END as prototype,\n    date(day) as count,\n    date(day) as time\nFROM generate_series($__timeFrom(), $__timeTo(), '1d'::interval) day\n         LEFT JOIN period p on daterange(date(p.start), date(p.\"end\"), '[]') @> date(day)\n         LEFT JOIN camp c on p.campid = c.id\nUNION ALL\nSELECT\n    'total' as prototype,\n    date(day) as count,\n    date(day) as time\nFROM generate_series($__timeFrom(), $__timeTo(), '1d'::interval) day\n         LEFT JOIN period p on daterange(date(p.start), date(p.\"end\"), '[]') @> date(day);"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Sommerlager 2026  (14. Juni - 31. August)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false\nand c.id in  (\n  select p.campid\n  from  period p\n  where p.end >  TO_DATE('20260614','YYYYMMDD')\n  and   p.start <  TO_DATE('20260831','YYYYMMDD')\n)"
    }
   ]
  },
  {
   "title": "Aktuell im Lager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false\nand exists (\n  select 1\n  from period p\n  where p.campid = c.id\n  and p.start <= now() \n  and p.end > now()\n)"
    }
   ]
  },
  {
   "title": "2025 SoLa",
   "type": "stat",
   "description": "14. Juni - 31. August",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false\nand c.id in  (\n  select p.campid\n  from  period p\n  where p.end >  TO_DATE('20250614','YYYYMMDD')\n  and   p.start <  TO_DATE('20250831','YYYYMMDD')\n)"
    }
   ]
  },
  {
   "title": "2024 SoLa",
   "type": "stat",
   "description": "15. Juni - 31. August",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1)\nfrom camp c\nwhere c.isprototype = false\nand c.id in  (\n  select p.campid\n  from  period p\n  where p.end >  TO_DATE('20240615','YYYYMMDD')\n  and   p.start <  TO_DATE('20240831','YYYYMMDD')\n)"
    }
   ]
  },
  {
   "title": "Anzahl erstellte Camps pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select date_trunc('day', c.createtime), count(1) \nfrom camp c\nwhere c.isprototype=false AND $__timeFilter(c.createtime)\t\ngroup by date_trunc('day', c.createtime)\norder by date_trunc('day', c.createtime)\n"
    }
   ]
  },
  {
   "title": "Total Camps by prototype",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    COALESCE(campPrototypeId, 'none')\n    WHEN 'f92fe1cd1ae9' THEN 'Basic'\n    WHEN '75b3572a338e' THEN 'J+S Lager DE'\n    WHEN '497f974e7d5d' THEN 'J+S Lager FR'\n    WHEN 'dffcb39cb4fb' THEN 'J+S Kurs DE'\n    WHEN 'fc8417239f9a' THEN 'J+S Kurs FR'\n    WHEN 'none' THEN 'No Prototype'\n    ELSE 'Other camp prototype'\n  END as campPrototype,\n  COUNT(*)\nFROM\n  camp\nGROUP BY\n  campPrototype\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Lager",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) as \"Zukünftige\"\nfrom camp c\nwhere c.isprototype = false\n  and exists (select 1\n              from period p\n              where p.campid = c.id\n                and (p.start > now()))"
    },
    {
     "rawSql": "SELECT COUNT(id) AS \"Total\" FROM camp WHERE isprototype = false LIMIT 50 "
    },
    {
     "rawSql": "select count(1) as \"Vergangen\"\nfrom camp c\nwhere c.isprototype = false\nand not exists (\n  select 1 \n  from  period p \n  where p.campid = c.id\n  and   p.end > now()\n)"
    }
   ]
  },
  { "title": "User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "New Users",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select date_trunc('week', u.createtime) as date, date_trunc('week', u.createtime) as count, case\n  when p.googleId is not null then 'Google'\n  when p.pbsmidataId is not null then 'PBS'\n  when p.cevidbId is not null then 'Cevi'\n  when p.jubladbId is not null then 'Jubla'\n  else 'eCamp'\nend as \"source\"\nfrom \"user\" u\nleft join \"profile\" p on p.id=u.profileid"
    }
   ]
  },
  {
   "title": "User-Verteilung",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "(select 'Google' name, count(1) from profile p where p.googleId is not null) union\r\n(select 'PBS' name, count(1) from profile p where p.pbsmidataId is not null) union\r\n(select 'Cevi' name, count(1) from profile p where p.cevidbId is not null) union\r\n(select 'Jubla' name, count(1) from profile p where p.jubladbId is not null) union\r\n(select 'eCamp' name, count(1) from profile p where p.googleId is null and p.pbsmidataId is null and p.cevidbId is null and p.jubladbId is null)\r\n  "
    }
   ]
  },
  {
   "title": "Anzahl User",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select INITCAP(u.state), count(1)\nfrom \"user\" u\ngroup by u.state  \nunion\nselect 'Total', count(1)\nfrom \"user\"\norder by 1"
    }
   ]
  },
  {
   "title": "Registrierungsverlauf",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select DATE_TRUNC('month', createtime) as createtime,\r\n       sum(case when name = 'Google' then count else 0 end) as \"Google\",\r\n       sum(case when name = 'PBS' then count else 0 end) as \"PBS\",\r\n       sum(case when name = 'Cevi' then count else 0 end) as \"Cevi\",\r\n       sum(case when name = 'Jubla' then count else 0 end) as \"Jubla\",\r\n       sum(case when name = 'eCamp' then count else 0 end) as \"eCamp\"\r\nfrom (\r\n  select 'Google' as name, DATE_TRUNC('day', createtime) as createtime, count(1) as count\r\n  from profile \r\n  where googleId is not null\r\n  group by DATE_TRUNC('day', createtime)\r\n\r\n  union all\r\n\r\n  select 'PBS' as name, DATE_TRUNC('day', createtime) as createtime, count(1) as count\r\n  from profile \r\n  where pbsmidataId is not null\r\n  group by DATE_TRUNC('day', createtime)\r\n\r\n  union all\r\n\r\n  select 'Cevi' as name, DATE_TRUNC('day', createtime) as createtime, count(1) as count\r\n  from profile \r\n  where cevidbId is not null\r\n  group by DATE_TRUNC('day', createtime)\r\n\r\n  union all\r\n\r\n  select 'Jubla' as name, DATE_TRUNC('day', createtime) as createtime, count(1) as count\r\n  from profile \r\n  where jubladbId is not null\r\n  group by DATE_TRUNC('day', createtime)\r\n\r\n  union all\r\n\r\n  select 'eCamp' as name, DATE_TRUNC('day', createtime) as createtime, count(1) as count\r\n  from profile \r\n  where googleId is null \r\n    and pbsmidataId is null \r\n    and cevidbId is null \r\n    and jubladbId is null\r\n  group by DATE_TRUNC('day', createtime)\r\n) as subquery\r\nWHERE createtime > TIMESTAMP '2023-02-01 00:00:00'\r\ngroup by DATE_TRUNC('month', createtime)\r\n"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    COUNT(*) AS profiles, \n    COALESCE(language, 'auto') AS language \nFROM \n    profile \nGROUP BY \n    COALESCE(language, 'auto') \nORDER BY \n    language DESC;\n"
    }
   ]
  },
  {
   "title": "New Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select INITCAP(u.state), count(1)\nfrom \"user\" u\nwhere $__timeFilter(u.createtime) \ngroup by u.state\nunion\nselect 'Total', count(1)\nfrom \"user\" u\nwhere $__timeFilter(u.createtime) \norder by 1"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_requests_total{server=\"srv0\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Exceeding Latency 500ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{server=\"srv0\"}[5m])) by (code)\n-\nsum(rate(caddy_http_request_duration_seconds_bucket{le=\"0.5\", server=\"srv0\"}[5m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Period / Duration in days",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE\n        WHEN duration <= 15 THEN duration + 1\n        ELSE 17\n        END AS duration_category,\n    count(*) AS count\nFROM (\n         SELECT\n             \"end\" - start AS duration\n         FROM\n             period\n     ) AS subquery\nGROUP BY\n    duration_category\nORDER BY\n    duration_category;"
    }
   ]
  },
  {
   "title": "Collaborators Created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', createtime) as time, COUNT(*) as \"Day\" FROM camp_collaboration GROUP BY time ORDER BY time;"
    },
    {
     "rawSql": "SELECT DATE_TRUNC('week', createtime) as time, COUNT(*) as \"Week\" FROM camp_collaboration GROUP BY time ORDER BY time;"
    }
   ]
  },
  {
   "title": "Camps created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT sum(case when campPrototypeId is null          then 1 else 0 end) \"no prototype\",\n       sum(case when campPrototypeId = 'f92fe1cd1ae9' then 1 else 0 end) \"Basic\",\n       sum(case when campPrototypeId = '75b3572a338e' then 1 else 0 end) \"J+S Lager DE\",\n       sum(case when campPrototypeId = '497f974e7d5d' then 1 else 0 end) \"J+S Lager FR\",\n       sum(case when campPrototypeId = 'dffcb39cb4fb' then 1 else 0 end) \"J+S Kurs DE\",\n       sum(case when campPrototypeId = 'fc8417239f9a' then 1 else 0 end) \"J+S Kurs FR\",\n       DATE_TRUNC('week', createtime) as                                  time\nFROM camp c\nGROUP BY time;"
    }
   ]
  },
  {
   "title": "ContentNodes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  ct.name,\n  count(content_node.id) as count\nFROM\n  content_node\n  LEFT JOIN content_type ct on ct.id = content_node.contenttypeid\nWHERE\n  content_node.id <> content_node.rootid AND\n  $__timeFilter(content_node.createtime)\nGROUP BY\n  ct.name\nORDER BY\n  count DESC;"
    }
   ]
  },
  {
   "title": "Camps with ContentNodes ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  ct.name,\n  COUNT(DISTINCT a.campid) AS count\nFROM\n  activity a\n  JOIN content_node cn ON cn.rootid = a.rootcontentnodeid -- all child nodes for that activity's root node\n  JOIN content_type ct ON ct.id = cn.contenttypeid\nWHERE\n  cn.id <> cn.rootid -- exclude the root node itself\nGROUP BY\n  ct.name\nORDER BY\n  count DESC;"
    }
   ]
  },
  {
   "title": "Camp creation before period start",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('day', c.createtime) as \"created\",\n    date_trunc('day', p.start) as \"period start\",\n    date(p.start) - date(c.createtime) + 1 AS \"created before period start\",\n    date(now()) - date(p.start) as startcolor\nFROM\n    period p\nLEFT JOIN camp c ON c.id = p.campId\nWHERE\n    date(p.start) - date(c.createtime) > -1 AND\n    $__timeFilter(c.createtime);\n"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Top URLs without query",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "escapedUrlWithoutQuery.keyword",
       "id": "2",
       "settings": { "min_doc_count": "100", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "json.httpRequest.request_time_seconds",
       "id": "6",
       "meta": {
        "avg": true,
        "count": true,
        "max": true,
        "min": true,
        "std_deviation": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "settings": {},
       "type": "extended_stats"
      },
      {
       "field": "json.httpRequest.request_time_seconds",
       "id": "7",
       "settings": {
        "percents": [
         "90",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "((escapedUrl: \"^app.ecamp3.ch/api\") OR (escapedUrl: \"^app.ecamp3.ch/print\")) and not escapedUrl : \"reset_password\" and not escapedUrl: \"activate\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Caching Hit Miss Ratio",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "escapedUrlWithoutQuery.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "json.handling.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "json.varnish_side : \"c\" AND NOT escapedUrlWithoutQuery: \"^app.ecamp3.ch/auth/\" AND NOT json.handling.keyword:\"synth\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Caching Hit Miss Ratio",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "20m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      },
      {
       "field": "json.handling.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "json.varnish_side : \"c\" AND NOT escapedUrlWithoutQuery: \"^app.ecamp3.ch/auth/\" AND NOT json.handling.keyword:\"synth\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ScheduleEntry Durations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT endoffset - startoffset as duration, count(DISTINCT activityId) FROM schedule_entry GROUP BY endoffset - startoffset;"
    }
   ]
  },
  {
   "title": "ScheduleEntry Durations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "rawSql": "SELECT endoffset - startoffset as duration, count(endoffset - startoffset) as \"count\" FROM schedule_entry WHERE endoffset - startoffset > 0 GROUP BY endoffset - startoffset;"
    }
   ]
  },
  {
   "title": "ContentNode Instanznamen",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT content_node.instancename AS \"×\", count(DISTINCT vcrcn.campId) as count\nFROM content_node\nJOIN VIEW_CAMP_ROOT_CONTENT_NODES vcrcn ON content_node.rootId = vcrcn.rootContentNodeId\nWHERE $__timeFilter(content_node.createtime) AND instancename is NOT NULL\nGROUP BY content_node.instancename\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Pfadinamen",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT nickname, COUNT(nickname) as \"count\" FROM profile GROUP BY nickname ORDER BY \"count\" DESC ;"
    }
   ]
  }
 ]
}