	<h1>DoctrineController</h1>



	<div class="span-18 colborder">
		<p>
			<a href="/doctrine/adduser">NewUser</a>
		</p>

		<table>

			<tal:block repeat="user users">
				<tr>
					<td tal:content="user/getId" />
					<td tal:content="user/getScoutname" />
					<td tal:content="user/getFirstname" />
					<td tal:content="user/getSurname" />

					<td>
						<a tal:attributes="href php: userForm.getEditLink(user.getId())">edit</a>
					</td>

				</tr>
			</tal:block>

		</table>
	</div>

	<div class="span-5 last">
		<tal:block content="structure userForm" />
	</div>