	<h1>DoctrineController</h1>

	<p>
		<a href="/doctrine/adduser">NewUser</a>
	</p>

	<table width="100%" border="1">

		<tal:block repeat="user users">
			<tr>
				<td tal:content="user/getId" />
				<td tal:content="user/getScoutname" />
				<td tal:content="user/getFirstname" />
				<td tal:content="user/getSurname" />

				<td>
					<a tal:attributes="href php: userForm.getEditLink(user.getId())">edit</a>
				</td>

			</tr>
		</tal:block>

	</table>

	<p>
		<tal:block content="structure userForm" />
	</p>