<span metal:define-macro="header">
	
	<tal:block condition="exists: group">
		<div class="group_logo">
			<img width="32" height="32" tal:attributes="src helper:url(array('group' => group.getId(), 'controller' => 'avatar', 'action' => 'group', 'size' => 32), 'general')" /><br />
		</div>
		
		<div class="group_header" tal:content="group/getDescription">GroupName</div>
		<div class="group_breadcrumb">
			
			<span tal:repeat="item group/getPathAsArray">
				<a tal:content="item/getDescription" tal:attributes="href helper:url(array('group' => item.getId() ), 'group')">GroupDescription</a> >>
			</span>
			
			<a tal:content="group/getDescription" tal:attributes="href helper:url(array('group' => group.getId() ), 'group')">GroupDescription</a> >>
			<tal:block content="camp/getTitle" />
		</div>
	</tal:block>
	
	
	<tal:block condition="exists: owner">
		<div class="user_logo">
			<img width="32" height="32" tal:attributes="src helper:url(array('user' => owner.getId(), 'controller' => 'avatar', 'action' => 'user', 'size' => 32), 'general')" /><br />
		</div>
	
		<div class="user_header" tal:content="owner/getDisplayName">UserDisplayName</div>
		<div class="user_breadcrumb">	
			<a tal:content="owner/getUsername" tal:attributes="href helper:url(array('user' => owner.getId() ), 'user')">UserName</a> >>
			<tal:block content="camp/getTitle" />
		</div>
	</tal:block>

	<nav id="mainnav">
		<tal:block content="structure php: this.navigation().menu().renderMenu(NULL, array('maxDepth' => 0, 'ulClass' => 'left'))" />
		<div class="clear" />
	</nav>
</span>
