<h2>My Camps:</h2>

<table>
	<tr tal:repeat="userCamp myUserCamps">
		<td><tal:block content="userCamp/getCamp/getId" /></td>
		<td><tal:block content="userCamp/getCamp/getName" /></td>

		<td><a tal:attributes="href '/camp/cancelFromCamp/${userCamp/GetId}'">Cancel From Camp</a></td>
	</tr>
</table>



<h2>All Camps</h2>

<p>
<a href="/camp/new">NewCamp</a>
</p>
	
<table>
	<tr tal:repeat="camp allCamps">
		<td><tal:block content="camp/getId" /></td>
		<td><tal:block content="camp/getName" /></td>
		<td><tal:block content="camp/getSlogan" /></td>

		<td><a tal:attributes="href '/camp/commitToCamp/${camp/getId}'">Commit To Camp</a></td>
		<td><a tal:attributes="href '/camp/edit/${camp/getId}'">Edit Camp</a></td>
		
	</tr>
</table>

