
<div class="span-24 last">
	<form tal:attributes="action helper:url(array('controller' =>'search', 'action' => 'searchuser'))">
		<input type="text" name="query" tal:attributes="value params/query|" />
		<input type="submit" value="Finden" />
	</form>
</div>

<div class="span-24 last">

	<div class="span-24 last">
		<h2 i18n:translate="">SearchResult:</h2>
		
		<tal:block repeat="user users">
			<span metal:use-macro="../dashboard/singleuser.phtml/withavatar" tal:define="user user" tal:omit-tag="" />
		</tal:block>
	</div>
	
</div>
