<div class="span-14">

	<div class="span-4">
		<img width="128" height="128" tal:attributes="src helper:url(array('action' => 'avatar', 'user' => user.getId(), 'size' => 128), 'user')" />
	</div>
	
	<div class="span-10 last">
		<h2 tal:content="user/getUsername" />
		<h3 tal:content="user/getFullName" />
		
		<!-- replace with ajax call one day -->
		<a tal:condition="php: me.canIAdd(user)" class="button" tal:attributes="href helper:url(array('action' => 'add', 'user' => user.getId()), 'user')">+add as friend</a> 
		<span tal:condition="php: me==user">Hey, this is you!</span>
		<span tal:condition="php: me.sentFriendshipRequestTo(user)">You have already sent a friendship request.</span>
		<tal:block condition="php: me.receivedFriendshipRequestFrom(user)">
			<span tal:content="user/getUsername" /> wants to be your friend.<br/>
			<a class="button" tal:attributes="href helper:url(array('action' => 'accept', 'user' => user.getId()), 'user')">+accept</a> 
			<a class="button" tal:attributes="href helper:url(array('action' => 'ignore', 'user' => user.getId()), 'user')">-ignore</a> 
		</tal:block>
		<tal:block condition="php: me.isFriendOf(user)">
			This is your friend! <br />
			<a class="button" tal:attributes="href helper:url(array('action' => 'divorce', 'user' => user.getId()), 'user')">-divorce</a> 
		</tal:block>
		
	</div>
	
	<div class="clear" />
	
	<p>
		<ul>
			<li>Email</li>
			<li>Address</li>
			<li>Personal stuff</li>
		</ul>
	</p>
	
	<div class="box">
		<h2>Groups</h2>
	</div>
	
	<div class="box">
		<h2>Camps</h2>
	</div>
	
	<div class="box">
		<h2>Shared</h2>
	</div>
	
</div>


<div class="span-10 last">
	<div tal:condition="php: me==user" class="right">
		<a class="button" href="#">Privacy Preferences</a> 
		<a class="button" href="#">Edit Profile</a> 
	</div>
	
	<div class="clear" />
	
	<div class="bigbox">
		<div class="title">Friends</div>
		<div class="content">
			<tal:block repeat="user friends">
				<span metal:use-macro="global/singleuser.phtml/withavatar" tal:define="user user" tal:omit-tag="" />
			</tal:block>
			
			<span tal:condition="php: count(friends)==0">Saidly, <span tal:content="user/getUsername" /> has no friends. But who cares, they are only virtual friends anyway.</span>
			
			<div class="clear" />
		</div>
	</div>
	
</div>