package com.example.demo.entities;// default package
// Generated Jun 20, 2021, 5:10:04 PM by Hibernate Tools 5.5.0.Final


import org.hibernate.annotations.Type;

import javax.persistence.*;
import java.util.Date;

/**
 * Camp generated by hbm2java
 */
@Entity
@Table(name = "camp"
        , catalog = "ecamp3dev"
)
public class Camp implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 16)
    private String id;

    @ManyToOne
    @JoinColumn(name = "creatorId", nullable = false)
    private User user;

    @Column(name = "campPrototypeId", length = 16)
    private String campPrototypeId;

    @Column(name = "isPrototype", nullable = false)
    private boolean isPrototype;

    @Column(name = "name", nullable = false, length = 32)
    private String name;

    @Column(nullable = false)
    @Type(type = "text")
    private String title;

    @Type(type = "text")
    private String motto;

    @Type(type = "text")
    private String addressName;

    @Type(type = "text")
    private String addressStreet;

    @Type(type = "text")
    private String addressZipcode;

    @Type(type = "text")
    private String addressCity;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createTime", nullable = false, length = 19)
    private Date createTime;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updateTime", nullable = false, length = 19)
    private Date updateTime;

    public Camp() {
    }


    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    public String getCampPrototypeId() {
        return this.campPrototypeId;
    }

    public void setCampPrototypeId(String campPrototypeId) {
        this.campPrototypeId = campPrototypeId;
    }


    public boolean isIsPrototype() {
        return this.isPrototype;
    }

    public void setIsPrototype(boolean isPrototype) {
        this.isPrototype = isPrototype;
    }


    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }


    public String getMotto() {
        return this.motto;
    }

    public void setMotto(String motto) {
        this.motto = motto;
    }


    public String getAddressName() {
        return this.addressName;
    }

    public void setAddressName(String addressName) {
        this.addressName = addressName;
    }


    public String getAddressStreet() {
        return this.addressStreet;
    }

    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }


    public String getAddressZipcode() {
        return this.addressZipcode;
    }

    public void setAddressZipcode(String addressZipcode) {
        this.addressZipcode = addressZipcode;
    }


    public String getAddressCity() {
        return this.addressCity;
    }

    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}


