package com.example.demo.entities;// default package
// Generated Jun 20, 2021, 1:35:51 PM by Hibernate Tools 5.5.0.Final


import javax.persistence.*;
import java.util.Date;
import java.util.Set;

/**
 * MailAddress generated by hbm2java
 */
@Entity
@Table(name = "mail_address"
        , catalog = "ecamp3dev"
        , uniqueConstraints = @UniqueConstraint(columnNames = "mail")
)
public class MailAddress implements java.io.Serializable {


    @Id
    @Column(name = "id", unique = true, nullable = false, length = 16)
    private String id;

    @Column(name = "state", nullable = false, length = 16)
    private String state;

    @Column(name = "mail", unique = true, nullable = false, length = 64)
    private String mail;

    @Column(name = "verificationCode", length = 64)
    private String verificationCode;

    public MailAddress() {
    }


    public MailAddress(String id, String state, String mail, Date createTime, Date updateTime) {
        this.id = id;
        this.state = state;
        this.mail = mail;
    }

    public MailAddress(String id, String state, String mail, String verificationCode, Date createTime, Date updateTime, Set usersForTrustedMailAddressId, Set usersForUntrustedMailAddressId) {
        this.id = id;
        this.state = state;
        this.mail = mail;
        this.verificationCode = verificationCode;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }


    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }


    public String getVerificationCode() {
        return this.verificationCode;
    }

    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode;
    }
}


