package com.example.demo.entities;// default package
// Generated Jun 20, 2021, 1:35:51 PM by Hibernate Tools 5.5.0.Final


import org.hibernate.annotations.Type;

import javax.persistence.*;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user"
        , catalog = "ecamp3dev"
        , uniqueConstraints = {@UniqueConstraint(columnNames = "trustedMailAddressId"), @UniqueConstraint(columnNames = "untrustedMailAddressId"), @UniqueConstraint(columnNames = "username")}
)
public class User implements java.io.Serializable {


    @Id
    @Column(name = "id", unique = true, nullable = false, length = 16)
    private String id;

    @ManyToOne()
    @JoinColumn(name = "trustedMailAddressId", unique = true)
    private MailAddress trustedMailAddress;

    @ManyToOne()
    @JoinColumn(name = "untrustedMailAddressId", unique = true)
    private MailAddress untrustedMailAddress;

    @Column(length = 32, unique = true)
    private String username;

    @Type(type = "text")
    private String firstname;

    @Type(type = "text")
    private String surname;

    @Type(type = "text")
    private String nickname;

    @Column(length = 16, nullable = false)
    private String state;

    @Column(length = 16, nullable = false)
    private String role;

    @Column(length = 20)
    private String language;

    public User() {
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    public MailAddress getTrustedMailAddress() {
        return this.trustedMailAddress;
    }

    public void setTrustedMailAddress(MailAddress mailAddressByTrustedMailAddressId) {
        this.trustedMailAddress = mailAddressByTrustedMailAddressId;
    }

    public MailAddress getUntrustedMailAddress() {
        return this.untrustedMailAddress;
    }

    public void setUntrustedMailAddress(MailAddress mailAddressByUntrustedMailAddressId) {
        this.untrustedMailAddress = mailAddressByUntrustedMailAddressId;
    }


    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }


    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }


    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }


    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }


    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }


    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }


    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

}


