package com.example.demo.entities;// default package
// Generated Jun 20, 2021, 1:35:51 PM by Hibernate Tools 5.5.0.Final


import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * UserIdentity generated by hbm2java
 */
@Entity
@Table(name = "user_identity"
        , catalog = "ecamp3dev"
        , uniqueConstraints = @UniqueConstraint(name = "identity", columnNames = {"provider", "providerId"})
)
public class UserIdentity implements Serializable {


    @Id
    @Column(name = "id", unique = true, nullable = false, length = 16)
    private String id;

    @ManyToOne()
    @JoinColumn(name = "userId", nullable = false)
    private User user;

    @Column(name = "provider", nullable = false)
    private String provider;

    @Column(name = "providerId", nullable = false)
    private String providerId;

    public UserIdentity() {
    }

    public UserIdentity(String id, User user, String provider, String providerId, Date createTime, Date updateTime) {
        this.id = id;
        this.user = user;
        this.provider = provider;
        this.providerId = providerId;
    }


    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    public String getProvider() {
        return this.provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }


    public String getProviderId() {
        return this.providerId;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

}


