name: check-renovate-config.yml
on:
  push:
    paths:
      - .github/workflows/check-renovate-config.yml
      - renovate.json
  pull_request:
    paths:
      - .github/workflows/check-renovate-config.yml
      - renovate.json

jobs:
  validate-renovate-config:
    name: 'renovate: validate config'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - run: docker run --rm -e LOG_LEVEL=debug -v "$PWD:/workspace" -w /workspace renovate/renovate:43.25.6 --platform=local
