name: check-renovate-config.yml
on:
  push:
    paths:
      - .github/workflows/check-renovate-config.yml
      - renovate.json
  pull_request:
    paths:
      - .github/workflows/check-renovate-config.yml
      - renovate.json

jobs:
  validate-renovate-config:
    name: 'renovate: validate config'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - run: docker run --rm -e LOG_LEVEL=debug -v "$PWD:/workspace" -w /workspace renovate/renovate:$RENOVATE_VERSION --platform=local
        env:
          # renovate: datasource=docker depName=renovate/renovate
          RENOVATE_VERSION: 44.39.3
