name: check-renovate-config.yml
on:
  push:
    paths:
      - .github/workflows/check-renovate-config.yml
      - renovate.json
  pull_request:
    paths:
      - .github/workflows/check-renovate-config.yml
      - renovate.json

jobs:
  validate-renovate-config:
    name: 'renovate: validate config'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - run: docker run --rm -e LOG_LEVEL=debug -v "$PWD:/workspace" -w /workspace renovate/renovate:$RENOVATE_VERSION --platform=local
        env:
          # renovate: datasource=docker depName=renovate/renovate
          RENOVATE_VERSION: 43.260.2
