name: Cleanup Old Caches
on:
  schedule:
    - cron: '34 3 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old caches
        uses: actions/github-script@v9
        with:
          script: |
            const sevenDaysAgo = new Date();
            sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

            const caches = await github.paginate(
              github.rest.actions.getActionsCacheList,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
              }
            );
            
            console.log(caches)

            console.log(`Found ${caches.length} cache entries across all pages`);

            let deletedCount = 0;

            for (const cache of caches) {
              console.log(`Processing cache:`, cache);
              const createdAt = new Date(cache.created_at);

              if (createdAt < sevenDaysAgo || true) {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });

                deletedCount++;
                console.log(`Deleted cache: ${cache.key} (${cache.id}), created at ${cache.created_at}`);
              }
            }

            console.log(`Deleted ${deletedCount} cache entries older than ${sevenDaysAgo.toISOString()}`);
