name: Cleanup Old Caches
on:
  schedule:
    - cron: '34 3 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old caches
        uses: actions/github-script@v9
        with:
          script: |
            const response = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            console.log("response", response);

            const sevenDaysAgo = new Date();
            sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

            for (const cache of response.data.caches.actions_caches) {
              console.log(`Cache data:`, cache);
              const createdAt = new Date(cache.created_at);
              if (createdAt < sevenDaysAgo) {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });
                console.log(`Deleted cache: ${cache.key}`);
              }
            }
