name: Deploy ingress

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: environment
        default: dev
      action:
        description: "Choose action"
        type: choice
        required: true
        default: diff
        options:
          - diff
          - deploy
  push:
    branches:
      - devel
    paths:
      - .github/workflows/deploy-ingress.yml
      - .ops/ingress/**

env:
  action: ${{ github.event.inputs.action || 'deploy' }}

jobs:
  deploy-ingress:
    name: "Deploy ingress"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup helm
        run: |
          mkdir ~/.kube && echo '${{ secrets.KUBECONFIG }}' > ~/.kube/config && chmod go-r ~/.kube/config

      - name: Add helm repositories
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update

      - name: Diff deployment
        run: |
          ./deploy.sh diff || true
        working-directory: .ops/ingress

      - name: Deploy
        if: env.action == 'deploy'
        run: |
          ./deploy.sh deploy
        working-directory: .ops/ingress
