name: CI + CD for staging and prod

on:
  push:
    branches:
      - staging
      - prod
    tags:
      - staging
      - prod
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        type: choice
        required: true
        default: diff
        options:
          - diff
          - deploy

jobs:
  build-and-push:
    name: Build and push docker images
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      tag: ${{ github.ref_name }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  upgrade-or-install-deployment:
    name: Upgrade or install deployment
    needs: build-and-push
    uses: ./.github/workflows/reusable-ecamp3-deployment.yml
    with:
      name: ${{ github.ref_name }}
      env: ${{ github.ref_name }}
      action: ${{ github.event.inputs.action || 'deploy' }}
    secrets: inherit
