name: CI + CD for devel

permissions:
  contents: read

on:
  push:
    branches:
      - devel
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action'
        type: choice
        required: true
        default: diff
        options:
          - diff
          - deploy

jobs:
  continuous-integration:
    name: 'Continuous integration'
    permissions:
      contents: write
      actions: write
      statuses: write
    uses: ./.github/workflows/continuous-integration.yml

  build-and-push:
    name: Build and push docker images
    needs: continuous-integration
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      tag: latest
    secrets:
      DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  upgrade-or-install-deployment:
    name: Upgrade or install deployment
    needs: build-and-push
    permissions:
      contents: read
      actions: read
      pull-requests: write
    uses: ./.github/workflows/reusable-ecamp3-deployment.yml
    with:
      name: dev
      env: dev
      action: ${{ github.event.inputs.action || 'deploy' }}
    secrets: inherit
