name: '[reusable only] ecamp3 deployment'

on:
  workflow_call:
    inputs:
      name:
        description: Deployment short name for subdomain (e.g. dev, pr123).
        required: false
        type: string
      sha:
        required: false
        type: string
        default: ${{ github.sha }}
      env:
        description: Target environment (dev, feature-branch, staging, prod)
        required: true
        type: string
      pr-number:
        required: false
        type: string
      dropDBOnUninstall:
        required: false
        type: boolean
        default: false
      restoreSourceFile:
        required: false
        type: string
      action:
        description: "Choose action of (diff|deploy)"
        type: string
        required: true
        default: diff

jobs:
  deploy-ecamp3:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    env:
      NAME: ${{ vars.NAME || inputs.name }}
      IMAGE_TAG: ${{ inputs.sha }}
      HELM_TIMEOUT: ${{ vars.HELM_TIMEOUT }}
    steps:
      - name: Get link to currently running job logs
        if: ${{ inputs.env == 'feature-branch' }}
        uses: Tiryoh/gha-jobid-action@v1.4.0
        id: job-url
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: Upgrade or install deployment / Deploy to Kubernetes

      - name: Create a pending GitHub deployment
        uses: bobheadxi/deployments@v1.5.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          env: ${{ inputs.env }}

      - name: Comment progress on PR
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ inputs.env == 'feature-branch' }}
        with:
          pr-number: ${{ inputs.pr-number }}
          message: |
            ### <span aria-hidden="true">🏗️</span> Feature branch deployment in progress


            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🔨</span> Latest commit | [${{ inputs.sha }}](https://github.com/${{ github.repository }}/commit/${{ inputs.sha }}) |
            |<span aria-hidden="true">🔍</span> Latest deploy log | [${{ steps.job-url.outputs.html_url }}](${{ steps.job-url.outputs.html_url }}) |
          comment-tag: feature-branch-deployment-status

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.sha }}

      - name: Dump secrets to /tmp/secrets.json
        run: |
          cat << 'EOF' | tee /tmp/secrets.json
          ${{ toJSON(secrets) }}
          EOF
          jq '.' /tmp/secrets.json

      - name: Dump variables to /tmp/vars.json
        run: |
          cat << 'EOF' | tee /tmp/vars.json
          ${{ toJSON(vars) }}
          EOF
          jq '.' /tmp/vars.json

      - name: Merge secrets, variables, and workflow inputs to env.yaml
        run: |
          jq -n \
            '{
              NAME: "${{ env.NAME }}",
              IMAGE_TAG: "${{ inputs.sha }}",
              RESTORE_SOURCE_FILE: "${{ inputs.restoreSourceFile || '' }}",
              DROP_DB_ON_UNINSTALL: ${{ inputs.dropDBOnUninstall }}
            }' > /tmp/additions.json
          jq -s '.[0] + .[1] + .[2]' /tmp/secrets.json /tmp/vars.json /tmp/additions.json > .helm/ecamp3/env.yaml
          jq '.' .helm/ecamp3/env.yaml

      - name: Setup kubectl authentication
        run: |
          mkdir -p ~/.kube
          echo '${{ secrets.KUBECONFIG }}' > ~/.kube/config
          chmod go-r ~/.kube/config

      - uses: ./.github/actions/setup-helmfile

      - name: Diff deployment
        run: |
          ./.helm/ecamp3/deploy.sh diff || true

      - name: Show values.yaml
        run: cat ./.helm/ecamp3/values.yaml

      - name: Deploy
        if: ${{ inputs.action == 'deploy' }}
        run: |
          ./.helm/ecamp3/deploy.sh deploy

      - name: Finish the GitHub deployment
        uses: bobheadxi/deployments@v1.5.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ format('https://{0}.{1}', env.NAME, vars.DOMAIN) }}
          env: ${{ steps.deployment.outputs.env }}

      - name: Get current time
        uses: josStorer/get-current-time@v2
        if: always()
        id: current-time
        with:
          timezone: Europe/Zurich

      - name: Comment success on PR
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ success() && inputs.env == 'feature-branch' }}
        with:
          pr-number: ${{ inputs.pr-number }}
          message: |
            ### <span aria-hidden="true">✅</span> Feature branch deployment ready!


            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">😎</span> **Deployment** | [https://${{ env.NAME }}.${{ vars.DOMAIN }}/](https://${{ env.NAME }}.${{ vars.DOMAIN }}/) |
            |<span aria-hidden="true">🔑</span> Login | `test@example.com` / `test` |
            |<span aria-hidden="true">🕒</span> Last deployed at | ${{ steps.current-time.outputs.readableTime }} |
            |<span aria-hidden="true">🔨</span> Latest commit | [${{ inputs.sha }}](https://github.com/${{ github.repository }}/commit/${{ inputs.sha }}) |
            |<span aria-hidden="true">🔍</span> Latest deploy log | [${{ steps.job-url.outputs.html_url }}](${{ steps.job-url.outputs.html_url }}) |
            |<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />![QR Code](https://api.qrserver.com/v1/create-qr-code/?size=180x180&ecc=H&format=svg&qzone=4&color=5-72-97&data=https://${{ env.NAME }}.${{ vars.DOMAIN }}/)<br /><br />_Use your smartphone camera to open QR code link._</details> |
            ---
          comment-tag: feature-branch-deployment-status

      - name: Comment failure on PR
        uses: thollander/actions-comment-pull-request@v3
        if: ${{ failure() && inputs.env == 'feature-branch' }}
        with:
          pr-number: ${{ inputs.pr-number }}
          message: |
            ### <span aria-hidden="true">💥</span> Feature branch deployment failed


            |  Name | Link |
            |---------------------------------|------------------------|
            |<span aria-hidden="true">🕒</span> Last attempted at | ${{ steps.current-time.outputs.readableTime }} |
            |<span aria-hidden="true">🔨</span> Latest commit | [${{ inputs.sha }}](https://github.com/${{ github.repository }}/commit/${{ inputs.sha }}) |
            |<span aria-hidden="true">🔍</span> Latest deploy log | [${{ steps.job-url.outputs.html_url }}](${{ steps.job-url.outputs.html_url }}) |
            ---
          comment-tag: feature-branch-deployment-status

      - name: Cleanup temp files
        if: always()
        run: rm -f /tmp/secrets.json /tmp/vars.json .helm/ecamp3/env.yaml
