name: 'Summarize changes on staging and prod PRs'

on:
  pull_request:
    branches: [staging, prod]

jobs:
  summarize-changes:
    name: Summarize changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Compute summary text
        id: summary
        run: |
          git fetch --all
          SUMMARY=$(git log origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} --merges --first-parent --perl-regexp --grep='from ecamp/renovate/' --invert-grep | grep 'Merge pull request' | awk '{print "- "$4}' | tac)
          echo "$SUMMARY"
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update PR description with summary
        uses: nefrob/pr-description@4dcc9f3ad5ec06b2a197c5f8f93db5e69d2fdca7 # v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          regex: ".*"
          regexFlags: s
          content: |
            ### <span aria-hidden="true">🏗️</span> Changes in this deployment

            Includes the following non-renovate PRs:
            ${{ steps.summary.outputs.summary }}

            <details>
            <summary><small>Code to generate this overview</small></summary>

            The above can be output locally using the following command:
            ```bash
            echo 'Includes the following non-renovate PRs:' && git log origin/${{ github.base_ref }}..origin/${{ github.head_ref }} --merges --first-parent --perl-regexp --grep='from ecamp/renovate/' --invert-grep | grep "Merge pull request" | awk '{print "- "$4}' | tac
            ```

            </details>
